Hamburger Icon and MENU Label Visibility Bug
meshery/meshery.io pull request #1107
Opened 2023-04-06 19:35 UTC by shaikahmadnawaz

**Title**

"[Footer] Use stellarnav.js instead of stellarnav.min.js in production"

**Description**

This PR addresses issue #1104 

The current implementation of the footer in production uses "/stellarnav.min.js", which causes issues with visibility of the MENU label. This PR modifies the environment conditional in the "footer.html" file to use "/js/stellarnav.js" instead. Alternatively, we can make `menuLabel: ""` from the "/stellarnav.min.js" file before this PR merge, which would also resolve the issue.

After merging this PR, the navbar will look like the screenshot attached:

![Screenshot (608)](https://user-images.githubusercontent.com/96189881/230474029-82715efb-ba62-4bce-9083-ea0df1fddd37.png)

**Notes for Reviewers**

Please review the changes made in the "footer.html" file and verify that they correctly modify the environment conditional to use "/js/stellarnav.js". Also, please ensure that the proposed alternative approach of modifying `menuLabel` in the "/stellarnav.min.js" file is a viable solution.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

2023-04-06 19:47 UTC, Chadha93 commented
It looks like this to me in Preview. 
![image](https://user-images.githubusercontent.com/65453826/230479667-1542e93c-3b9c-46aa-92e8-f1a84df641a8.png)

2023-04-06 19:52 UTC, shaikahmadnawaz commented
> It looks like this to me in Preview. ![image](https://user-images.githubusercontent.com/65453826/230479667-1542e93c-3b9c-46aa-92e8-f1a84df641a8.png)

I did for mobile view

2023-04-06 19:57 UTC, shaikahmadnawaz commented
> It looks like this to me in Preview. ![image](https://user-images.githubusercontent.com/65453826/230479667-1542e93c-3b9c-46aa-92e8-f1a84df641a8.png)

It is coming like that until the page fully loaded, after loading you can see the preview like this 👇

![Screenshot (609)](https://user-images.githubusercontent.com/96189881/230481173-7ab49bbe-d20d-485c-8362-ceeb0a30de0c.png)

2023-04-07 00:58 UTC, shaikahmadnawaz commented
**Updated the code** and this is the screenshot of the deploy [preview link](https://deploy-preview-1107--mesheryio-preview.netlify.app/)  in mobile mode of hamburger menu.

![Screenshot (610)](https://user-images.githubusercontent.com/96189881/230518989-bc96cd29-9acc-4cd8-8a22-fb78a33b1f55.png)

2023-04-07 08:27 UTC, Udit-takkar requested changes
Thanks for contributing @shaikahmadnawaz 

1) while clicking on hamburger icon the complete box shouldn't be blue.

https://user-images.githubusercontent.com/53316345/230572119-d51ba9d1-0d9a-4627-92c6-5428d8df83d9.mov

2) when the dropdown menu is open we should display a cross icon instead of hamburger icon with some animation. you can see https://layer5.io/ for reference.

2023-04-07 08:34 UTC, Udit-takkar commented on _includes/footer.html
> -<script src="{{ site.baseurl }}/js/stellarnav.min.js"></script>
i don't think this change is correct. in production environment we should use .min.js file because they are minified version of js file

2023-04-07 08:35 UTC, Udit-takkar commented on _includes/footer.html
> -<script src="{{ site.baseurl }}/js/stellarnav.min.js"></script>
stellarnav.min.js is auto generated from stellarnave.js.

2023-04-07 09:49 UTC, shaikahmadnawaz commented
Okay I will work on this updates

2023-04-07 09:50 UTC, shaikahmadnawaz commented
> Thanks for contributing @shaikahmadnawaz
> 
> 1. while clicking on hamburger icon the complete box shouldn't be blue.
> 
> 2. when the dropdown menu is open we should display a cross icon instead of hamburger icon with some animation. you can see https://layer5.io/ for reference.

Okay I will work on these updates

2023-04-07 10:30 UTC, Udit-takkar commented
@shaikahmadnawaz yeah your solution is correct but these changes are required for better experience.

2023-04-07 10:33 UTC, shaikahmadnawaz commented
> @shaikahmadnawaz yeah your solution is correct but these changes are required for better experience.

Yes, updating them also 😊

2023-04-10 10:36 UTC, vishalvivekm commented
> > @shaikahmadnawaz yeah your solution is correct but these changes are required for better experience.
> 
> Yes, updating them also 😊

@shaikahmadnawaz Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-04-10 15:22 UTC, shaikahmadnawaz commented
> > > @shaikahmadnawaz yeah your solution is correct but these changes are required for better experience.
> > 
> > 
> > Yes, updating them also 😊
> 
> @shaikahmadnawaz Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

Someone already added it, I think it's you.

2023-04-14 04:57 UTC, vishalvivekm commented
> > > > @shaikahmadnawaz yeah your solution is correct but these changes are required for better experience.
> > > 
> > > 
> > > Yes, updating them also 😊
> > 
> > 
> > @shaikahmadnawaz Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)
> 
> Someone already added it, I think it's you.

Hi @shaikahmadnawaz, let's discuss this in the next Websites call on 17th April 5:30 PM IST: [meeting minutes ](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

2023-04-15 21:25 UTC, GaganpreetKaurKalsi reviewed
Hey @shaikahmadnawaz, instead of updating the whole `stellarnav.min.js`, can't we just remove the `menuLabel:"Menu"` from the `stellarnav.min.js` file or set it to empty string? That should work.

2023-04-16 05:33 UTC, shaikahmadnawaz reviewed
Check once @GaganpreetKaurKalsi, `menuLabel:"Menu"` is set to empty string

2023-04-16 06:12 UTC, GaganpreetKaurKalsi commented
> Check once @GaganpreetKaurKalsi, `menuLabel:"Menu"` is set to empty string

Yeah, that's true. What I am saying is that currently under Files changed tab, the whole file contents are updated(surely the `menuLabel: ""` ). The changes include formatting changes(spaces, newLine, semi-colon, etc.) for readability purposes and setting `menuLabel: ""`. Minified files should not have any formatting changes. 

Just update the menuLabel value, `menuLabel: ""`. Don't include any formatting related changes. You can disable the prettier if it is troubling you.

2023-04-16 06:22 UTC, shaikahmadnawaz commented
> > Check once @GaganpreetKaurKalsi, `menuLabel:"Menu"` is set to empty string
> 
> Yeah, that's true. What I am saying is that currently under Files changed tab, the whole file contents are updated(surely the `menuLabel: ""` ). The changes include formatting changes(spaces, newLine, semi-colon, etc.) for readability purposes and setting `menuLabel: ""`. Minified files should not have any formatting changes.
> 
> Just update the menuLabel value, `menuLabel: ""`. Don't include any formatting related changes. You can disable the prettier if it is troubling you.

Okay, got it 👍

2023-04-16 07:07 UTC, closed without merging

2023-06-30 12:49 UTC, Savio629 commented
Any reason @shaikahmadnawaz for closing this pr?

2023-07-02 05:54 UTC, shaikahmadnawaz commented
I raised new PR.