configuration of help-modal and import instruction on each catelog page
meshery/meshery.io pull request #1114
Opened 2023-04-12 13:05 UTC by sudhanshutech

**Description**

This PR fixes 
1. Dark mode issue of help-modal under import design link and improve styling of code-blocks in mesheryctl tab

Earlier:

https://user-images.githubusercontent.com/90546692/231464856-ff940bb5-b7bc-4533-9fbe-871650a86ac0.mp4

Current:

https://user-images.githubusercontent.com/90546692/231465401-2c09fa8e-81ed-46e6-a35d-626318f70051.mp4

2. This pr fixes #1113 
Adding modal for instruction to import design

https://user-images.githubusercontent.com/90546692/231466051-a595e9a1-adbc-464a-8427-41a4c5703648.mp4

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-13 18:50 UTC, sudhanshutech commented
@leecalcote are you referring same context in this issue #1113

2023-04-13 19:21 UTC, leecalcote commented on _includes/help-modal.html
> +  font-size: 22px;
@sudhanshutech let's prefer `rem` over `px`.

Let's also prefer `flex` over `absolute`.

2023-04-13 20:18 UTC, sudhanshutech commented on _includes/help-modal.html
> +  font-size: 22px;
okay

2023-04-14 21:33 UTC, vishalvivekm commented on js/main.js
We don't need to add this functionality again here, as we already have it in [/footer.html](https://github.com/meshery/meshery.io/blob/master/_includes/footer.html#:~:text=%3C/script%3E-,%3Cscript%3E,%3C/script%3E,-%3Cscript%3E)

Just make sure that the `data-clipboard-target` attribute on the Copy button element button specifies the target of the clipboard copy operation i.e. it should reference the id of the container element that holds the text to be copied ( like if we want to copy the text inside the `div` element with an `id` of `"start-pattern"`, we need to specify `data-clipboard-target="#start-pattern"` in the copy button element which currently is set to "#start-brew" if you notice)

2023-04-14 21:34 UTC, vishalvivekm commented
Great work @sudhanshutech 👏 on enhancing the dark mode support for the help-modal.
After a thorough review of all the changes made,  Here are my findings that I'd wanna share:

as per the [Deploy Preview](https://deploy-preview-1114--mesheryio-preview.netlify.app/):
1. The word "Note" in import instruction on each catalog page is invisible in light mode and also that extra "
<img width="348" alt="Screenshot 2023-04-15 011405" src="https://user-images.githubusercontent.com/110674407/232141963-c4669f36-9372-4f4c-baba-941a98940cba.png">

2. on [Homepage](https://meshery.io/) in getting-started section: the copy btn's feedback has changed to:
<img width="211" alt="Screenshot 2023-04-12 190431" src="https://user-images.githubusercontent.com/110674407/232136586-e44b2c6c-a7bb-4a12-808d-35b38425c1eb.png">
3. It may not be an issue but,  in the help modal, the tooltip overlaps with the button ( I'll leave this one upto you to decide)
<img width="136" alt="Screenshot 2023-04-15 014239" src="https://user-images.githubusercontent.com/110674407/232146483-ca98c77f-d9d0-453e-99c8-ba99ed35e2da.png">


Now Please Note: We've copy buttons on:
   - getting started section on homepage, 
   - in help-modal
   -  on each catalog page. 

And we already have a well [implemented functionality](https://github.com/meshery/meshery.io/blob/master/_includes/footer.html#:~:text=%3C/script%3E-,%3Cscript%3E,%3C/script%3E,-%3Cscript%3E) that deals with the btn's feedbacks and copying text with it . so adding more of it won't do us any good ig.

2023-04-15 20:53 UTC, GaganpreetKaurKalsi requested changes
Adding to @vishalvivekm's observations, 
another issue that I spotted, when you click on any platform on the mainPage, the tooltip showing 'platform name' changes to `copied`.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/232252633-454c4db4-e8eb-41d9-ae0c-e47d530168e9.png">

2023-04-16 17:12 UTC, vishalvivekm commented
@sudhanshutech How about we discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-04-17 12:14 UTC, sudhanshutech commented on js/main.js
@vishalvivekm #start-pattern is parent div so if i target that the copy button is going inconsistent actually, so i have not disturbed the id already there.

2023-04-17 12:18 UTC, sudhanshutech commented
> Great work @sudhanshutech 👏 on enhancing the dark mode support for the help-modal. After a thorough review of all the changes made, Here are my findings that I'd wanna share:
> 
> as per the [Deploy Preview](https://deploy-preview-1114--mesheryio-preview.netlify.app/):
> 
> 1. The word "Note" in import instruction on each catalog page is invisible in light mode and also that extra "
> 
> <img alt="Screenshot 2023-04-15 011405" width="348" src="https://user-images.githubusercontent.com/110674407/232141963-c4669f36-9372-4f4c-baba-941a98940cba.png">
> 
> 2. on [Homepage](https://meshery.io/) in getting-started section: the copy btn's feedback has changed to:
> 
> <img alt="Screenshot 2023-04-12 190431" width="211" src="https://user-images.githubusercontent.com/110674407/232136586-e44b2c6c-a7bb-4a12-808d-35b38425c1eb.png">
> 
> 3. It may not be an issue but, in the help modal, the tooltip overlaps with the button ( I'll leave this one upto you to decide)
> <img alt="Screenshot 2023-04-15 014239" width="136" src="https://user-images.githubusercontent.com/110674407/232146483-ca98c77f-d9d0-453e-99c8-ba99ed35e2da.png">
> 
> Now Please Note: We've copy buttons on:
> 
> * getting started section on homepage,
> * in help-modal
> * on each catalog page.
> 
> And we already have a well [implemented functionality](https://github.com/meshery/meshery.io/blob/master/_includes/footer.html#:~:text=%3C/script%3E-,%3Cscript%3E,%3C/script%3E,-%3Cscript%3E) that deals with the btn's feedbacks and copying text with it . so adding more of it won't do us any good ig.

on 2 point @vishalvivekm from my side 
![image](https://user-images.githubusercontent.com/90546692/232481692-aa733caa-2c1f-4638-aa56-f2aa46257e10.png)

2023-04-17 12:25 UTC, sudhanshutech commented
@vishalvivekm 
![image](https://user-images.githubusercontent.com/90546692/232483366-77801f90-7d35-45c6-b4e9-b9ecd048865a.png)

2023-04-19 11:58 UTC, sudhanshutech commented on js/main.js
@vishalvivekm what i referring was this as per your suggetion

https://user-images.githubusercontent.com/90546692/233067496-70a8daeb-3f3b-4792-96d7-38162b1d6a65.mp4

2023-04-19 12:49 UTC, sudhanshutech commented
> Adding to @vishalvivekm's observations, another issue that I spotted, when you click on any platform on the mainPage, the tooltip showing 'platform name' changes to `copied`.
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/54144759/232252633-454c4db4-e8eb-41d9-ae0c-e47d530168e9.png">

that i guess is resolved because its not been visible in live site

2023-04-27 10:14 UTC, sudhanshutech commented
@vishalvivekm i guess this pr is good to go , any more updates? So that that bug will not create a problem

2023-05-01 06:34 UTC, vishalvivekm commented
@sudhanshutech I'm afraid the aforementioned issues are yet to be addressed and that's why this PR isn't Merge-ready here: 

Also, there are some changes made in this area in some other PRs that were recently merged, so I think it'd be great if you close this and update your local with the upstream and then start afresh with the changes. 

It'll be helpful if you could discuss this on websites call but as you've your exams, so no sweat :)

2023-06-01 12:52 UTC, leecalcote commented
@sudhanshutech feel free to reopen should your focus return to this issue.

2023-06-01 12:52 UTC, closed without merging