fix: unexpected extra width - UI for mobile devices
meshery/meshery.io pull request #1159
Opened 2023-05-13 13:24 UTC by aminoxix

**Description**
fixed unexpected extra width by reducing the `min-width` to `360px`, also, standardized the navbar with good practice by moving the mode toggle button to `navigation.html`

This PR fixes #995 

**Notes for Reviewers**
"We should migrate this to vanilla HTML, CSS & JS to impact more contributors instead Jekyll, if possible!"

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-05-13 20:07 UTC, GaganpreetKaurKalsi approved these changes
Things are working fine. Looks good 👍 💯 
Great work done @aminoxix 🥇 Saw the conversation in issue, pretty long pending I would say.
Finally it would get fixed 🚀

2023-05-14 05:28 UTC, aminoxix commented
@GaganpreetKaurKalsi what's your insights on the reviewer's note?

2023-05-14 08:25 UTC, GaganpreetKaurKalsi commented
@leecalcote Would you like me to exercise my merging powers here?

2023-05-23 09:09 UTC, thisiskaransgit reviewed
Thank you @aminoxix, for this update, since this change will affect the responsiveness globally, there are things to consider
- at < 360px in /the features section, there's an overflow issue for the SMP button,  
![Screenshot from 2023-05-23 14-14-38](https://github.com/meshery/meshery.io/assets/92504666/e3db8092-324f-4ebf-932c-a0ccc01dfd1a)
 - Changes in the left margin affect other components
   - table has shifted to left in /talks-and-presentations
   ![Screenshot from 2023-05-23 14-33-11](https://github.com/meshery/meshery.io/assets/92504666/d55f303c-bf55-461a-aba7-b847e592e833)

   - filter button in /catalog section has moved toward the left, rather than in center
![Screenshot from 2023-05-23 14-31-23](https://github.com/meshery/meshery.io/assets/92504666/64ec7c3c-6d12-40c8-9776-2df9116afe02)

Kindly look into it and update the PR and we are good to go.

2023-05-23 20:06 UTC, aminoxix commented
Hey @thisiskaransgit,
1. very catchy, I might say I would be more tho as I fixed one more button on the same page! 👀 

2. but, yeah I think according to you & website, it seems `/catalog` page "Filter button" is working fine for me (quite the same as the [deploy preview](https://deploy-preview-1159--mesheryio-preview.netlify.app/catalog)).

![image](https://github.com/meshery/meshery.io/assets/75872316/d8b1df5c-c1b0-4554-963e-b13ca96d8658)

3. well, the same for `/talks-and-presentations`, do you want me to fix "Find video and slides here" button to `center`? If so, then I think mate, this PR is already ready to merge, and we can track other broken components via another issue. // @leecalcote 

![image](https://github.com/meshery/meshery.io/assets/75872316/dbf4ccd8-b092-4ace-bd6d-ef33136705b9)

Well, I checked it for all mobile screens, seems all looks good!

2023-05-23 20:22 UTC, leecalcote commented
> @leecalcote Would you like me to exercise my merging powers here?

@GaganpreetKaurKalsi I missed this note earlier. Yes, if you're comfortable with this change, then please do merge.

2023-05-24 18:58 UTC, thisiskaransgit requested changes
@aminoxix, thank you for incorporating the changes and looking up for additional things to fix.
-  for the `/catalog` section, remove the left padding for the filter wrapper from the media query at about 700 px.

2023-05-24 18:58 UTC, thisiskaransgit commented on _includes/header.html
> -              id="logo-dark-light"
revert the addition of whitespaces please

2023-05-26 15:25 UTC, thisiskaransgit requested changes
@aminoxix, Changes made in the header have resulted in the toggle icon being relatively smaller than desired, it would be better to revert the changes made here, 
**Current:** 
![Screenshot from 2023-05-26 20-14-49](https://github.com/meshery/meshery.io/assets/92504666/24719fd0-a214-42a5-bae6-c03da2ca55cf)
**Preview:** 
![Screenshot from 2023-05-26 20-18-35](https://github.com/meshery/meshery.io/assets/92504666/d7e6ba97-c2fa-4b9b-ae0d-3beaf81ea489)

- Remove the unnecessary white spaces and extra lines, included in the commits 
- The performance-wrapper is inconsistent for 750-800 px, but there's already a PR open for this and we don't want you to steal their limelight, so please revert this one too.
-  make sure that you're not pushing any unwanted changes, so this can be the last revision.

2023-05-26 19:50 UTC, aminoxix commented
> @aminoxix, Changes made in the header have resulted in the toggle icon being relatively smaller than desired, it would be better to revert the changes made here, **Current:** ![Screenshot from 2023-05-26 20-14-49](https://user-images.githubusercontent.com/92504666/241251482-24719fd0-a214-42a5-bae6-c03da2ca55cf.png) **Preview:** ![Screenshot from 2023-05-26 20-18-35](https://user-images.githubusercontent.com/92504666/241251799-d7e6ba97-c2fa-4b9b-ae0d-3beaf81ea489.png)
> 
>     * Remove the unnecessary white spaces and extra lines, included in the commits
> 
>     * The performance-wrapper is inconsistent for 750-800 px, but there's already a PR open for this and we don't want you to steal their limelight, so please revert this one too.
> 
>     * make sure that you're not pushing any unwanted changes, so this can be the last revision.

I came across an issue in the header file where the toggle mode SVG element was located. It should actually be placed within the navigation section. In order to improve the visual aspect, I made adjustments by reducing its size since it appeared too large on the navigation bar and had unnecessary empty space around it.

Response to your reviews:
- I understand that there are unexpected indentations in the source code. Although I made sure to fix unnecessary white spaces and extra lines for the specific lines I worked on, it would be helpful if you could highlight that all spaces in this pull request should be addressed. I'm more than willing to fix them all for you.
- Regarding the performance-wrapper, I addressed the spacing issue because you raised it in this pull request. That's why I mentioned discussing those concerns separately and not within this PR. (already mentioned above in point 3 [here](https://github.com/meshery/meshery.io/pull/1159#issuecomment-1560054253))
- Could you please provide more clarity on what you mean by "unwanted changes"? It caught my attention, and I'm genuinely curious about the specific aspects you are referring to.

2023-05-28 15:28 UTC, vishalvivekm commented
@aminoxix 
Let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

2023-05-29 09:30 UTC, aminoxix commented
hey @vishalvivekm, thanks for taking this up, but I'm done with this issue now, if anyone wanna work or just approve, it's open! (:

2023-06-17 10:10 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-06-25 05:23 UTC, thisiskaransgit commented
@leecalcote @Chadha93, we're good to go with this one !

2023-06-25 06:09 UTC, aminoxix commented
@thisiskaransgit: https://github.com/meshery/meshery.io/pull/1159#issuecomment-1560073123

2023-06-27 13:34 UTC, Chadha93 approved these changes
LGTM

2023-06-27 13:34 UTC, merged