Changes in filter on catalog page for mobile devices
meshery/meshery.io pull request #1186
Opened 2023-06-09 21:21 UTC by Savio629

**Description**
Changes in filter on catalog page for mobile devices

This PR fixes #1185 

**Notes for Reviewers**
Draft pr

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-06-11 19:01 UTC, Savio629 commented
@vishalvivekm @thisiskaransgit Do we need to add 'View all' Button?

2023-07-02 20:35 UTC, Savio629 commented
Ummm build is failing.....

For the meantime: 

https://github.com/meshery/meshery.io/assets/91362589/96dd1186-6224-484f-a7a5-e667305e1a56

2023-07-10 02:32 UTC, Savio629 commented
@thisiskaransgit why is build still failing?

2023-07-19 20:45 UTC, thisiskaransgit commented
@Savio629, Thank you for working on this, this was put on hold to complete the integration update task. We can move now with this one. Kindly resolve the merge conflicts.

2023-07-21 02:45 UTC, Savio629 commented
@thisiskaransgit Will resolve the conflicts and update you by the end of the day or mostly by tomorrow 👍

2023-07-21 17:45 UTC, Savio629 commented
@thisiskaransgit

2023-07-22 10:16 UTC, GaganpreetKaurKalsi requested changes
Hey @Savio629, 
1. I see these characters at the right side of the screen
<img width="1440" alt="image" src="https://github.com/meshery/meshery.io/assets/54144759/32d34fe8-6502-475f-bf80-a133484ad631">

2. Also, we might want to have `cursor: pointer;` for "View All" button.
3. Maybe decrease of spacing between filters and also have them in a single column instead of 2 as in phones with smaller screen widths, the content is overflowing. Or if we want to have 2 columns, it should become one when the content overflows. 
<img width="322" alt="image" src="https://github.com/meshery/meshery.io/assets/54144759/f179f959-bfe9-4d46-b30f-1b9985b300f3">

<br><br>

**Let's wait to hear from others as well on point 3.**

2023-07-22 14:15 UTC, Savio629 commented
Fixed 1st and 2nd issue 👍
Regarding the 3rd issue, there wasn't any issue earlier but as I pulled the new changes just saw that it was not coded in such a way to avoid overflowing,I'll fix it..
I think as screen width decreases it should be in a single column

2023-07-22 17:29 UTC, Savio629 commented
@GaganpreetKaurKalsi I have made the changes regarding the 3rd point
Also there are two deployment categories

2023-07-28 18:30 UTC, GaganpreetKaurKalsi commented
> // @thisiskaransgit @GaganpreetKaurKalsi Any other changes required?


See the first row of Cards, it is being cut  @Savio629 
<img width="1440" alt="image" src="https://github.com/meshery/meshery.io/assets/54144759/4e2076de-b6f5-4cd6-8694-eafda10b5791">

2023-07-30 16:01 UTC, Savio629 commented
@GaganpreetKaurKalsi Done👍

2023-08-06 10:20 UTC, GaganpreetKaurKalsi approved these changes
Looks good @Savio629 👍

2023-08-06 18:55 UTC, thisiskaransgit approved these changes

2023-08-06 18:55 UTC, thisiskaransgit commented on _layouts/catalog.html
> +  {% include card-modal.html %}
```suggestion
  <!-- {% include card-modal.html %}   -->
```

2023-08-06 18:56 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-08-06 18:56 UTC, thisiskaransgit commented on _layouts/catalog.html
> +  {% include card-modal.html %}
@Savio629, keep them disabled

2023-08-16 18:50 UTC, Chadha93 commented
Merge conflicts @Savio629 ...

2023-08-16 18:50 UTC, Chadha93 commented
@vishalvivekm A good one for your :eyes:

2023-08-23 20:33 UTC, Chadha93 commented
@Savio629 Heads up merge conflicts...

2023-09-10 16:41 UTC, Savio629 commented
// @thisiskaransgit

2023-09-10 18:14 UTC, leecalcote commented
@Savio629, you'll need to coordinate with @Chadha93. @thisiskaransgit is inactive in the community and project.

2023-09-11 14:08 UTC, Chadha93 commented
@vishalvivekm Will you review this PR? I asked at our last meeting too. 

I'll review this tonight. cc @Savio629

2023-10-12 01:57 UTC, Savio629 commented
@Chadha93 @vishalvivekm

2023-10-12 13:45 UTC, leecalcote commented
Thanks, @Savio629. 

The formatting of the cards in mobile view could use you help. 
![Uploading IMG_8745.png…]()

2023-10-12 13:49 UTC, merged