added "Changing Release-Channels" blog
meshery/meshery.io pull request #1224
Opened 2023-06-27 11:40 UTC by Mohith234

**Description**

This PR fixes #1207 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-06-30 16:45 UTC, thisiskaransgit requested changes
@Mohith234
- Make sure you are using relevant tags for code blocks
example: [meshery.io/#getting-started](https://meshery.io/#getting-started)
- Keep the thumbnail on the top, similar to [layer5.io/blog](https://meshery.io/#getting-started)
- Review and fix the formatting bugs

2023-06-30 19:13 UTC, Mohith234 commented
Hey @thisiskaransgit , I have some followup questions 
- Changing the thumbnail to the top disturbs the uniformity design for the list of blogs in this page https://meshery.io/blog. Is it ok still ?
- Also I've tried to incorporate the tags from here [meshery.io/#getting-started](meshery.io/#getting-started) But there it was a html doc and it got rendered as a code. Here it is not rendering a code block when `<code>` tag is used. Preview of that file in VS Code works fine but the output on the site doesn't match.

2023-07-02 08:21 UTC, vishalvivekm commented
@Mohith234 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-07-04 15:26 UTC, thisiskaransgit commented
@Mohith234, use the raw html elements in the markdown file for `copy to clipboard` 
```html
<div id="div-id" class="highlight-code">
  <code class="code-box">mesheryctl system context create docker --platform docker --set
    mesheryctl system start</code>
    <!-- copy to clipboard -->
    <a class="btn tooltip" style="position: absolute; top:0.10rem; right: 0.5rem; font-size: 22px;" data-clipboard-target="#div-id"
      data-clipboard-text="mesheryctl system context create docker --platform docker --set
      mesheryctl system start" onmouseout="resetCopyText(this)">
      <i class="far fa-copy"></i>
      <span class="tooltiptext" style="font-size: 15px; width: 140px; height: 40px; padding: 0; line-height: 40px; top: 2rem; left: -80px;">Copy to clipboard</span>
    </a>
  </div>
```

2023-07-05 06:32 UTC, vishalvivekm commented
@Mohith234 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-07-07 18:16 UTC, thisiskaransgit requested changes

2023-07-07 18:58 UTC, Mohith234 commented on collections/_posts/2023-06-16-changing-meshery-release-channels.md
> +author_contributor: Karan Thakur
@thisiskaransgit couldn't find the cause of the issue. I guess we need to change the author or @leecalcote could help with this on where this default comes from.

2023-07-07 19:16 UTC, Mohith234 commented
For now, I have removed the `author_contributor` field and by default, it shows Lee Calcote as an author.

Do review the other parts and let's close it 👍

// @thisiskaransgit

2023-07-07 19:28 UTC, thisiskaransgit requested changes

2023-07-07 19:28 UTC, thisiskaransgit commented on _sass/blog.scss
> +		border-bottom: 1px solid #00B39F;
```suggestion
		border-bottom: 1px solid var(--brand-color-secondary);
```

2023-07-07 19:28 UTC, thisiskaransgit commented on _sass/blog.scss
> +		background: #00B39F;
```suggestion
		background:  var(--brand-color-secondary);
```

2023-07-07 19:28 UTC, thisiskaransgit commented on _sass/blog.scss
> +    color: #fff;
```suggestion
    color:  var(--color-white);
```

2023-07-07 19:47 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-07-09 07:25 UTC, samyakshah3008 commented
@Mohith234 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

2023-07-09 08:22 UTC, Mohith234 commented
@samyakshah3008 I believe this PR has been completed and is ready to merge.

2023-07-26 08:39 UTC, thisiskaransgit commented
@Chadha93, we're good to go with this PR

2023-07-26 08:49 UTC, Chadha93 approved these changes
Thank you, gents.

2023-07-26 08:50 UTC, merged