[Site] [Dark Mode] Update import catalog modal according to theme #1203
meshery/meshery.io pull request #1247
Opened 2023-07-02 05:19 UTC by vaibhav-xt

**Description**
There is no option left except this. If we declare a sass variable, it conflicts with the dark and light theme colors. @sudhanshutech has tried before this is pr #1114 and it was closed. 
This PR fixes #1203 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2023-07-02 08:29 UTC, vishalvivekm commented
hmm build is failing..
@vaibhav-xt Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

2023-07-09 07:23 UTC, samyakshah3008 commented
@vaibhav-xt  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

2023-07-18 05:41 UTC, vaibhav-xt commented
Hello @samyakshah3008 & @Chadha93, please get a review and I think it's ready to merge.

2023-07-18 06:48 UTC, Chadha93 requested changes

2023-07-18 06:48 UTC, Chadha93 commented on _sass/catalog.scss
> +  color: #000;
use theme ref

2023-07-18 06:48 UTC, Chadha93 commented on _sass/catalog.scss
> +  color: #fff;
here too

2023-07-24 17:33 UTC, Chadha93 commented
@vaibhav-xt Review changes pending...

2023-07-25 18:43 UTC, thisiskaransgit commented
Hey @vaibhav-xt, thank you for your efforts here. The implemented change does not go well with the website.
- The change of text color is desirable, what we need to change is the modal color according to the theme, the same way we implemented it in the catalog modal. This change will be easily done by referencing the color variable.
 ````scss
   background-color: var(--brand-color-secondary);
 ````

- For the coming soon card, 
 1. Remove the declaration of h5 style from `programs.scss` and add it to the element style file
 ```scss
h4, h5, h6{
	color: var(--color-secondary-dark);
}
``` 
 1. Make the style consistent, by removing the background shade.
 
 The issue that you described was due to the presidency of styles, by following the above steps it will be fixed for this section.

2023-07-25 19:10 UTC, thisiskaransgit requested changes
Hey @vaibhav-xt, thank you for your efforts here. The implemented change does not go well with the website.
- The change of text color is desirable, what we need to change is the modal color according to the theme, the same way we implemented it in the catalog modal. This change will be easily done by referencing the color variable.
 ````scss
   background-color: var(--integrations-bg);
 ````
  Also, change the tab heading color to Kepple green
- For the coming soon card, 
 1. Remove the declaration of h5 style from `programs.scss` and add it to the element style file
 ```scss
h4, h5, h6{
	color: var(--color-secondary-dark);
}
``` 
 2. Make the style consistent, by removing the background shade.
 3. Change the overlay-text to be dark mode compatible
 
 The issue that you described was due to the presidency of styles, by following the above steps it will be fixed for this section.

2023-07-28 07:50 UTC, Chadha93 reviewed
@vaibhav-xt Please also add links to meshery docs for UI and mesherctl in the modal section.

2023-07-29 13:23 UTC, thisiskaransgit reviewed
Hey @vaibhav-xt, Rest of the changes looks good, but the pattern-id is not visible 

 in _sass/catalog.scss
 Remove color style
 ```scss
pattern-id-overlay{
color: white
}
``` 
Do this and we're done here

2023-07-30 21:05 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-08-06 18:44 UTC, thisiskaransgit reviewed
@Chadha93

2023-08-06 18:44 UTC, thisiskaransgit commented on _includes/help-modal.html
> +            <h3><a href="https://docs.meshery.io/project/contributing/contributing-cli">Meshery CLI</a></h3>
```suggestion
            <h3>Meshery CLI</h3>
            <p>To use mesheryctl follow the steps mentioned in the <a href="https://docs.meshery.io/installation/mesheryctl">docs</a></p>
            
```

2023-08-06 18:44 UTC, thisiskaransgit commented on _includes/help-modal.html
> +            <h3><a href="https://docs.meshery.io/project/contributing/contributing-ui">Meshery UI</a></h3>
```suggestion
            <h3>Meshery UI</h3>
            <p>To install Meshery follow the steps mentioned in the  <a href="https://docs.meshery.io/installation/quick-start#install-meshery">docs</a></p>
            
```

2023-08-16 18:38 UTC, Chadha93 commented on _includes/help-modal.html
> +            <p>To install Meshery follow the steps mentioned in the  <a href="https://docs.meshery.io/installation/quick-start#install-meshery">docs</a></p>
```suggestion
            <p>To import designs, visit <a href="https://docs.meshery.io/guides/meshery-design#import-your-designs">docs</a></p>
```

2023-08-16 18:39 UTC, Chadha93 commented on _includes/help-modal.html
> +            <p>To use mesheryctl follow the steps mentioned in the <a href="https://docs.meshery.io/installation/mesheryctl">docs</a></p>
```suggestion
            <p>Import using mesheryctl, visit <a href="https://docs.meshery.io/installation/mesheryctl">docs</a> for steps.</p>
```

2023-08-16 18:42 UTC, merged