Styled the scrollbar in homepage
meshery/meshery.io pull request #1281
Opened 2023-07-11 15:33 UTC by Faizan711

**Description**
Styled the scrollbar in the home page with site's primary color.

This PR fixes #1257

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-16 09:54 UTC, vishalvivekm commented
@Faizan711 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-07-22 04:58 UTC, HarshDobariya79 reviewed
Are the changes in the Gemfile necessary @Faizan711? If not can you please revert it?

2023-07-28 21:08 UTC, Chadha93 commented on Gemfile.lock
> -    ffi (1.15.5-x64-mingw32)
@Faizan711 Please revert this Gemfile.lock change.

2023-07-28 21:10 UTC, Chadha93 requested changes

2023-07-28 21:10 UTC, Chadha93 commented on _includes/home-page.html
> +      background-color: #00B39F;
@Faizan711, please use theme ref color, I see this color is in our brand guide, if it's not in them you can add it and then use it.

2023-08-15 19:15 UTC, Chadha93 commented
Hi @Faizan711, this issue is resolved by @Ghat0tkach. You might want to review his PR. Let's close this issue, feel free to take new assignments. Thanks.

2023-08-15 19:15 UTC, closed without merging