6th section of community page w/signoff
meshery/meshery.io pull request #1305
Opened 2023-07-18 08:51 UTC by ayushsinha25

**Description**

This PR fixes #1271 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-18 21:59 UTC, thisiskaransgit requested changes
@ayushsinha25, thank your for your efforts

2023-07-18 21:59 UTC, thisiskaransgit commented on community.html
> +        on all meetings and events.
```suggestion
          Join Meshery’s meeting from anywhere in the world! We you missed any of our events we have it recorded on our Youtube channel. You can also subscribe to our community calendar to stay up-to-date on all meetings and events.
```

2023-07-18 21:59 UTC, thisiskaransgit commented on community.html
> +        <div class="logoss" style="display: flex;align-items: center;justify-content: left;">
```suggestion
        <div class="logos" style="display: flex;align-items: center;justify-content: left;">

```
- Consider renaming the classes, please. 
- Also, look for the globally available elements

2023-07-18 21:59 UTC, thisiskaransgit commented on assets/images/logos/YouTube-dark.svg
I am pretty sure the youtube logo (both the dark and light) looks chipped off.

2023-07-18 21:59 UTC, thisiskaransgit commented on community.html
> +        <h1 style="font-family: 'Qanelas Soft', sans-serif; font-size: 3vmax; margin-bottom: 20px; margin-top: 20px;">Meshery Community <br>Meetings and Events</h1>
Keep the heading in the center when the container arrangement changes, for smaller screens.

2023-07-20 03:34 UTC, leecalcote commented
Keep up the good work, @ayushsinha25

2023-07-20 05:18 UTC, ayushsinha25 commented
> @ayushsinha25, thank your for your efforts 

Should I make all those changes that you have recommended? And a new pr? @thisiskaransgit

2023-07-20 07:12 UTC, sudhanshutech commented
Lets consider this pr for merge i guess and raise another issue for enahancements // @thisiskaransgit @vishalvivekm

2023-07-20 07:12 UTC, sudhanshutech approved these changes

2023-07-22 13:51 UTC, Rexford74 approved these changes
You've put in a good shift, @ayushsinha25. Well done!

2023-07-22 20:02 UTC, ayushsinha25 commented
> You've put in a good shift, @ayushsinha25. Well done!

Thanks man!!!

2023-07-24 08:49 UTC, vishalvivekm commented
@ayushsinha25 
We could not cover this in the last call, Please add it in today's websites call [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)
Let's discuss this today.

2023-07-28 08:55 UTC, thisiskaransgit approved these changes
We will be soon moving ahead with merging each section. Looks good to merge, thank you for your contribution 🎉

2023-07-28 21:29 UTC, Chadha93 commented
merge conflicts @ayushsinha25

2023-07-30 18:26 UTC, Ghat0tkach commented
hii @ayushsinha25 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Make sure to attend tommorow's website call for review

2023-07-30 18:27 UTC, ayushsinha25 commented
> hii @ayushsinha25 
> 
> Let's discuss it on the websites call.
> Please add this as an agenda item in the meeting minutes, if you would :)
> 
> https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima
> 
> Make sure to attend tommorow's website call for review 

Ya, sure

2023-08-01 01:02 UTC, vishalvivekm commented
@ayushsinha25 please resolve the conflicts so that we can proceed with merging your efforts here.

2023-08-01 02:21 UTC, ayushsinha25 commented
> @ayushsinha25 please resolve the conflicts so that we can proceed with merging your efforts here.

Fine, will do it by Today evening

2023-08-01 17:09 UTC, ayushsinha25 commented
> @ayushsinha25 please resolve the conflicts so that we can proceed with merging your efforts here.

done

2023-08-15 18:23 UTC, thisiskaransgit commented
Great job on your PR @ayushsinha25! Your efforts and contributions to the project are highly appreciated.
Just wanted to inform you that we will be closing this PR as another one with similar changes has been merged. Please know that this decision does not diminish the value of your work.
Keep up the fantastic work, and we look forward to seeing more of your contributions in the future!

2023-08-15 18:23 UTC, closed without merging