updates features section
meshery/meshery.io pull request #1313
Opened 2023-07-23 20:13 UTC by thisiskaransgit

**Description**

This PR fixes 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-28 21:39 UTC, Chadha93 requested changes
Thanks @thisiskaransgit, I recently few updates to the features on[ layer5](https://layer5.io/cloud-native-management/meshery) will you compare and update accordingly in this PR?

2023-07-29 06:48 UTC, Savio629 commented on collections/_pages/features.html
> +    <p>Meshery is not just an application. It is a set of microservices where the central component is itself called Meshery. Integrators may extend Meshery by taking advantage of designated Extensio
application, it is

2023-07-29 06:51 UTC, Savio629 commented
@thisiskaransgit Also I feel the cloud native catalog card images doesn't go well with the gray background
![tempdel](https://github.com/meshery/meshery.io/assets/91362589/244722a8-1292-4bc3-8beb-988363957c65)

2023-07-30 18:28 UTC, Ghat0tkach commented
hii @thisiskaransgit 


Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-08-15 18:58 UTC, Chadha93 reviewed
@thisiskaransgit Matched the features on Layer5.io?

2023-08-15 19:54 UTC, thisiskaransgit commented
@Chadha93 I did

2023-08-16 18:45 UTC, Chadha93 requested changes
@thisiskaransgit It's still different, please match the points from here - https://layer5.io/cloud-native-management/meshery
![image](https://github.com/meshery/meshery.io/assets/65453826/6832bd92-e355-4c43-abe0-00840557a385)

2023-08-16 20:42 UTC, thisiskaransgit commented
@Chadha93, thanks for pointing out, two points were left to update, did that. Additionally, there was a design issue after updating the branch to the latest, which I fixed.

2023-08-16 20:55 UTC, Chadha93 approved these changes

2023-08-16 20:55 UTC, merged