fixed step number for dark mode
meshery/meshery.io pull request #1331
Opened 2023-07-28 16:50 UTC by ranjanmangla1

**Description**

This PR fixes #1214

Now the step numbers are clearly visible:
![image](https://github.com/meshery/meshery.io/assets/93506927/5a64de32-f66f-489c-b669-9f19202de0d0)

present condition on meshery.io site: 
![image](https://github.com/meshery/meshery.io/assets/93506927/6454bd89-da23-48e2-9905-c27491d0021c)

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-28 20:25 UTC, Chadha93 commented on Gemfile.lock
> -      google-protobuf (~> 3.21)
This can be reverted. @ranjanmangla1

2023-07-29 14:46 UTC, thisiskaransgit requested changes
@ranjanmangla1, the changes look good, revert the dependency changes

2023-07-30 09:31 UTC, Ghat0tkach commented
Hii @ranjanmangla1 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-08-15 19:45 UTC, thisiskaransgit commented
PR abandoned...

2023-08-15 19:45 UTC, closed without merging