Clarification in README.md Regarding 'bundle install' Execution #1338
meshery/meshery.io pull request #1347
Opened 2023-08-06 08:28 UTC by YashRajSingh-4799

**Description**
Updated the Readme file regarding "Bundle install" command Execution

This PR fixes #1338

**Notes for Reviewers**
the bundle install command was used at two places in Readme file and Makefile.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-07 17:41 UTC, thisiskaransgit requested changes
@YashRajSingh-4799 Thanks, please update the make site's execution command in readme too.

2023-08-08 05:31 UTC, YashRajSingh-4799 commented
Hi @thisiskaransgit, 
the makesite command execution is updated now in readme

2023-08-08 13:49 UTC, iArchitSharma commented
@YashRajSingh-4799 

> Hi @thisiskaransgit, the makesite command execution is updated now in readme

@YashRajSingh-4799  It looks like there's a misunderstanding in the way you're trying to combine the commands.
The Syntax you are using is invalid, use `&&` to combine two commands
Nevertheless, it might be more effective to specify both commands separately:
 `$ bundle install`
 `$ bundle exec jekyll serve --drafts --livereload`

2023-08-08 14:28 UTC, YashRajSingh-4799 commented
> @YashRajSingh-4799
> 
> > Hi @thisiskaransgit, the makesite command execution is updated now in readme
> 
> @YashRajSingh-4799 It looks like there's a misunderstanding in the way you're trying to combine the commands. The Syntax you are using is invalid, use `&&` to combine two commands Nevertheless, it might be more effective to specify both commands separately: `$ bundle install` `$ bundle exec jekyll serve --drafts --livereload`



Updated the Makefile commands!!!

Sorry, it was written in the issue that the command is used twice so i just remove the bundle install command. i havnt seen the Makefile command. 
Thank for the review....

2023-08-08 14:48 UTC, thisiskaransgit commented on README.md
> +  _Note: From the Makefile, this command is actually running `$ bundle install exec jekyll serve --drafts --livereload`_
@YashRajSingh-4799 @iArchitSharma, this was the change I requested

2023-08-08 14:54 UTC, thisiskaransgit commented on Makefile
Changes in makefile is not needed @iArchitSharma

2023-08-08 16:14 UTC, iArchitSharma commented
I guess its good to go now
Thank you @YashRajSingh-4799

2023-08-08 16:15 UTC, thisiskaransgit approved these changes
@YashRajSingh-4799 Looks good, thank you for the quick fix :tada:

2023-08-08 17:09 UTC, iArchitSharma approved these changes

2023-08-08 17:10 UTC, iArchitSharma approved these changes

2023-08-16 18:56 UTC, Chadha93 approved these changes

2023-08-16 18:56 UTC, merged