Resolving Design Requests in Community page
meshery/meshery.io pull request #1354
Opened 2023-08-11 12:08 UTC by thisiskaransgit

**Description**

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-13 16:17 UTC, vishalvivekm commented
@thisiskaransgit Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-08-15 14:55 UTC, thisiskaransgit commented on _includes/modal.html
> +        <p>{{pattern.patternInfo | replace: '\\n', '<br/>'| replace: '\n', '<br/>' }}</p>
```suggestion
        <p>{{pattern.patternInfo}}</p>
```

2023-08-15 14:55 UTC, thisiskaransgit commented on _includes/partials/individual-component.html
> +    <p>{{pattern.patternInfo | replace: '\\n', '<br/>'| replace: '\n', '<br/>' }}</p>
```suggestion
    <p>{{pattern.patternInfo}}</p>
```

2023-08-15 19:03 UTC, Chadha93 commented on collections/_pages/community.html
> +    <a href="https://slack.meshery.io/" class="highlight">Welcome Aboard</a>
```suggestion
    <a href="https://slack.meshery.io/" class="highlight">Join Our Talented Community</a>

```

2023-08-15 19:04 UTC, Chadha93 commented on collections/_pages/community.html
> +      <p class="heading">Empower Yourself</p>
```suggestion
      <p class="heading">The Meshery Community!</p>

```

2023-08-15 19:04 UTC, Chadha93 commented on collections/_pages/community.html
> +      <p class="heading">Empower Yourself</p>
Make it H1

2023-08-15 19:05 UTC, Chadha93 commented on collections/_pages/community.html
> +      <p class="community-heading">Engage, Contribute, and Make a Difference</p>
Make this sub-heading of H1

2023-08-15 19:05 UTC, Chadha93 commented on collections/_pages/community.html
> +  <p class="paragraph">More than just a community of contributors, we are also a support system</p>
```suggestion
  <p class="paragraph">Warm, welcoming, and encouraging. Embrace developer-defined infrastructure and help empower every engineer with us.</p>

```

2023-08-15 19:06 UTC, Chadha93 commented on collections/_pages/community.html
>    <p class="paragraph para2">We Know you'll need all the help you can get, and we provide it through.</p>
```suggestion
```

2023-08-15 19:07 UTC, Chadha93 commented on collections/_pages/community.html
>        <h4 class="handbook-header">EXPLORE THE LAYER5 COMMUNITY</h4>
```suggestion
      <h4 class="handbook-header">Jump in. The community is warm and welcoming!</h4>

```

2023-08-15 19:09 UTC, Chadha93 commented on collections/_pages/community.html
> +      <p class="handbook-paragraph">The community is growing at a tremendous rate. We value our connections and that is what makes us unique. Whether it is your first meeting or your tenth contributi
```suggestion
      <p class="handbook-paragraph">With active members from around the globe, the community is a collection of diverse open source contributors, each of whom espouse our cultural values of inclusivity and paying it forward for others. We welcome individuals at all stages of their development and of all walks of life. Every member is encourage to embrace these values and support one another in meaningfully and consistently advancing the community's open source initiatives.</p>

```

2023-08-15 19:12 UTC, Chadha93 requested changes
@thisiskaransgit The hero section needs work on the graphic (cc @Rexford74 @ritiksaxena124), let's use some of the white space.

The button seems inconsistent.

2023-08-22 09:00 UTC, closed without merging