updated catalog modal design
meshery/meshery.io pull request #1360
Opened 2023-08-15 12:49 UTC by thisiskaransgit

**Description**

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2023-08-15 14:57 UTC, thisiskaransgit commented on _includes/modal.html
> +        <p>{{pattern.patternInfo | replace: '\\n', '<br/>'| replace: '\n', '<br/>' }}</p>
```suggestion
        <p>{{pattern.patternInfo}}</p>
```

2023-08-15 14:57 UTC, thisiskaransgit commented on _includes/partials/individual-component.html
> +    <p>{{pattern.patternInfo | replace: '\\n', '<br/>'| replace: '\n', '<br/>' }}</p>
```suggestion
    <p>{{pattern.patternInfo}}</p>
```

2023-08-15 18:49 UTC, Chadha93 requested changes
@thisiskaransgit Alignment and padding issues in the header. Also, let's get clear on the placement of x, it's odd to have it on the left, I'm aware of the design that we have a badge on the top-right. 

Just to confirm, did we ever had a complete UX and design made for this modal? cc @ritiksaxena124 
![image](https://github.com/meshery/meshery.io/assets/65453826/234ac212-7959-40bd-a817-2d9746f5c8f1)

2023-08-15 19:53 UTC, thisiskaransgit commented
> @thisiskaransgit Alignment and padding issues in the header. Also, let's get clear on the placement of x, it's odd to have it on the left, I'm aware of the design that we have a badge on the top-right.
> 
> Just to confirm, did we ever had a complete UX and design made for this modal? cc @ritiksaxena124 ![image](https://user-images.githubusercontent.com/65453826/260808138-234ac212-7959-40bd-a817-2d9746f5c8f1.png)

@Chadha93 No major design was needed here, and the placement of elements on the position was intentional. The suggestion was provided in Slack, since the last PR wasn't concluded with all the requests, this one was needed. 

<summary>
<details>

1. note the need for a different color for the “X”(previously it was black)
2. You might add a bit of space between the design diagram and the buttons or put the buttons at the bottom of the modal.
3. or put an outline around the diagram’s screenshot (which are all the same right now, but will become MeshMap Snapshots)
4. Note the disjointed type label in the Related Patterns card (something to fix (bring inline with the rest of the design)). (edited) 
5. Do not use bold text.
6. Change the color of the external link button, too.
7. give it some space between the card name and make is the larger to be almost the same size as the card name.
8. The white space between the card name and the first “WHAT THIS PATTERN….” is wasted and can be cut-down.
9. The “Related Patterns” section title can be captialized.
10. Finally, if you move the screenshot, buttons and related patterns back to the left side, where they were, you can vertically split the card into two sections such that the left side has a different background than the main card, providing clarity to the user, making it easier to digest the information. (edited) 
11. It's fine to keep the card name in bold.

</details>
</summary>

2023-08-15 20:10 UTC, ritiksaxena124 commented
Suggestion: we should show only relevant details on modal not all details because what is the point of having a separate page when we are showing all details on modal

2023-08-16 18:31 UTC, Chadha93 approved these changes

2023-08-16 18:31 UTC, merged