Copied Blogs from smp-spec.io to meshery.io/blog
meshery/meshery.io pull request #1405
Opened 2023-09-02 21:56 UTC by akhilender-bongirwar

**Description**

This commit implements the solution to the issue regarding the migration of blogs from https://smp-spec.io/ to https://meshery.io/blog. The blogs have been successfully copied while preserving the original publication date and author's name.

Changes Made:

- Copied blogs from https://smp-spec.io/ to https://meshery.io/blog.
- Ensured that the original publication date and author's name are maintained.

This PR fixes #1395 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-09-03 16:57 UTC, vishalvivekm commented
@akhilender-bongirwar 
Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

2023-09-05 07:50 UTC, Mohith234 requested changes
- There are some places where an unordered list is used instead of an ordered list, like in `Meshmark Explained` and `Getting Started with SMP Analysis`. Could you check them?
- Also, reduce the space between the image and the text below it. They are set wide apart on the home page [ `/blog` page ]
- On the `Pipelining Service Mesh Specifications` the code snippet lacks indentations in the code which are highly important. Please fix them.

The rest looks good to me @akhilender-bongirwar

2023-09-05 11:44 UTC, akhilender-bongirwar commented
Hi @Mohith234 , I have reviewed and made the required change. Please check : ) ... Thank you

2023-09-05 14:00 UTC, Mohith234 commented
Still, the indentation in the code didn't get fixed [ 3rd point mentioned above ] 

// @akhilender-bongirwar

2023-09-05 14:33 UTC, akhilender-bongirwar commented
> Still, the indentation in the code didn't get fixed [ 3rd point mentioned above ]
> 
> // @akhilender-bongirwar

Sorry @Mohith234 , didn't notice that the prettier in my vscode was doing it. I will fix that soon.... : )..

2023-09-06 19:12 UTC, akhilender-bongirwar commented
Hey @Mohith234 ,  Could you please check the changes.. : )...

2023-09-09 14:49 UTC, Mohith234 requested changes
- To make the text look consistent, change the text color to default with the other text. Attached a screenshot of the `Meshmark Explained` blog post. The same goes for `Analyzing with SMP` 

![image](https://github.com/meshery/meshery.io/assets/88539464/73e8f6ba-b31e-4e18-a963-5fcadb8f800f)

- The headings inside the `Analyzing with SMP` blog can be made larger. Maybe h2 or h3 would look better IMO. What do you think? @akhilender-bongirwar 

- In `Pipelining Service mesh specifications` this is a wrong syntax remove the space before the `name`
![image](https://github.com/meshery/meshery.io/assets/88539464/9285eb82-4c5e-48a2-9812-159904d7a5b2)

2023-09-09 15:07 UTC, Mohith234 commented
Sorry for the late reply. I pointed out some of the things to improve above, please look into them and discuss your opinion on incorporating those changes. 

Also, is there any other way of adding indentations other than adding `&nbsp` for the indentations part?

// @akhilender-bongirwar

2023-09-09 19:29 UTC, akhilender-bongirwar commented
Hey @Mohith234 no problem. I have just seen the reviews

- The text being inconsistent in light mode maybe has occured due to other pull request #1407 . I will fix that soon. 
- Yeah, the headings in `Analysing with SMP`  with h3 will look good IMO.
- I have copied the exact indentations as it was there in the `https://smp-spec.io/blog/spec/pipelining-service-mesh-specifications`
The screenshot of the original indentations for the Pipelining Service Mesh Specifications
![Screenshot 2023-09-10 004059](https://github.com/meshery/meshery.io/assets/112749383/0717954a-e770-47d4-996b-0347091d1f12)
The original one also has an extra space for `name`.


- Only `&nbsp;` is working for the indentations part or I can reduce the &nbsp; by `&ensp; = two &nbsp;`
`&emsp; = four &nbsp;` . If there is any other more feasible alternative please let me know  : ).

2023-09-09 20:53 UTC, Mohith234 commented
- About the 3rd point I checked the code using YAML validator so removing the space gives valid code so..
- About reducing `&nbsp` 's , go ahead it reduces a bit of excessive code.

2023-09-11 11:40 UTC, Mohith234 reviewed
All good to go, made some suggestions take a look into them.

P.S Great work on the code snippets

2023-09-11 11:41 UTC, Mohith234 commented on collections/_posts/2016-07-20-the-process-for-direct-sales.md
> +<div class="row" style="width:220px;float:right;padding:5px;text-align:center;">
- This blog is not listed I guess
```suggestion
<div class="row" style="width:220px;float:right;padding:20px;text-align:center;">
```

2023-09-11 11:42 UTC, Mohith234 commented on collections/_posts/2023-06-16-changing-meshery-release-channels.md
> +<div style="text-align:center;padding:5px">
```suggestion
<div style="text-align:center;padding:20px">
```

2023-09-11 11:42 UTC, Mohith234 commented on collections/_posts/2023-01-09-meshery-system-provider.md
> +<div style="text-align:center;padding:5px">
```suggestion
<div style="text-align:center;padding:20px">
```

2023-09-11 11:42 UTC, Mohith234 commented on collections/_posts/2021-04-26-validating-smi-conformance-with-meshery.md
> +<div class="row" style="width:220px;float:left;padding:5px;text-align:center;">
```suggestion
<div class="row" style="width:220px;float:left;padding:20px;text-align:center;">
```

2023-09-18 13:38 UTC, akhilender-bongirwar commented
Hey @Mohith234, could you please review the pr as I have implemented all the suggested changes as you said.

2023-09-18 18:12 UTC, Mohith234 approved these changes
Awesome work done @akhilender-bongirwar 

Looks good to me 🚀

2023-09-28 10:08 UTC, leecalcote commented
Merge conflict...

2023-10-07 18:53 UTC, vishalvivekm requested changes
@leecalcote 
The link was broken updated it with : https://layer5.io/projects/service-mesh-performance

2023-10-07 18:53 UTC, vishalvivekm commented on collections/_posts/2020-05-21-meshmark-explained.md
> +            Another aspect here is the need for distributed, multi-mesh and workload performance management. Distributed load testing offers insight into system behaviors that arguably more accuratel
```suggestion
            Another aspect here is the need for distributed, multi-mesh and workload performance management. Distributed load testing offers insight into system behaviors that arguably more accurately represent real-world behaviors of services under load as that load comes from any number of sources. This aim of enhancing the current load generation and analysis techniques to include distributed load testing is hoped to be achieved by the <a href="https://layer5.io/projects/service-mesh-performance">Distributed Performance Management of Service Meshes</a> project, by analyzing and working hand in hand with Nighthawk, a versatile HTTP load testing tool.
```

2023-10-07 21:17 UTC, vishalvivekm commented on collections/_posts/2022-01-26-pipelining-service-mesh-specifications.md
> +Participating service mesh projects can also <a href="https://docs.meshery.io/functionality/service-mesh-interface#reporting-conformance">automatically report their conformance test results</a> to th
```suggestion
Participating service mesh projects can also <a href="https://docs.meshery.io/tasks/service-mesh-interface#reporting-conformance">automatically report their conformance test results</a> to the <a href="https://meshery.io/service-mesh-interface">SMI Conformance dashboard</a>
```

2023-10-07 21:43 UTC, vishalvivekm commented on _sass/layout.scss
> -    white-space: pre-line;
This causes:
![Screenshot from 2023-10-08 03-00-33](https://github.com/meshery/meshery.io/assets/110674407/b12b648e-3f1a-4974-9601-b77f9b5d4fcb)

2023-10-07 21:51 UTC, vishalvivekm commented on _sass/layout.scss
> +    white-space: pre-wrap;
```suggestion
    white-space: pre-line;
```

2023-10-07 21:55 UTC, vishalvivekm approved these changes

2023-10-07 21:59 UTC, merged