feat: introduce sorting to catalogs page
meshery/meshery.io pull request #1481
Opened 2023-10-28 11:53 UTC by Lucif3r-in

**Description**

This PR fixes #1355 

**Notes for Reviewers**
Introduced sorting for catalogs page

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-10-28 11:55 UTC, Lucif3r-in commented
@iArchitSharma @abhijeetgauravm Check this PR it has all changes you suggested

2023-10-28 12:30 UTC, abhijeetgauravm reviewed
Just for maintaining the consistency can we do either small letter one items first before capital letter one items or after the capital letter one items??

As we can see here its not maintaining the consistency here?
Here small letter one items are before capital letter one items
![image](https://github.com/meshery/meshery.io/assets/65087356/99b1dcbf-48ab-4df5-a449-a33eb130933b)

But here capital letter one items are before small letter one items. Can we make it consistent everywhere like whether before or after ??
![image](https://github.com/meshery/meshery.io/assets/65087356/0416ac9a-6b90-4e52-848e-72b88af8e008)

![image](https://github.com/meshery/meshery.io/assets/65087356/5bb09760-f034-492a-9fa5-9c436e9d7c85)

2023-10-28 12:37 UTC, Lucif3r-in commented
Sort feature here is converting all to lowercase then following the sort procedure. For the second photo, it checks that the first letter is same then converts the second letter to lowercase and compares it. Do we need to change this? @abhijeetgauravm

2023-10-28 12:50 UTC, abhijeetgauravm commented
> Sort feature here is converting all to lowercase then following the sort procedure. For the second photo it converts all to lowercase, then it checks that the first letter is same then compares the second letter and arranges the cards according to it. Do we need to change this? @abhijeetgauravm . If so, then I think we have to do ASCII comparison🤔, will do as you say

No sweat @Lucif3r-in great work so far, i think its good in this case too but let's get feedback of others on this too.

2023-10-28 12:54 UTC, abhijeetgauravm requested changes
Can we have proper margin here as well, as we have in case of All and deployment. As we can see the item is touching to the technologies part on the left in the below cases here!
![image](https://github.com/meshery/meshery.io/assets/65087356/1e36814c-96d3-409e-a93d-eb8ee84e989e)
![image](https://github.com/meshery/meshery.io/assets/65087356/603cb17a-2fba-43da-b595-bd01dcae11f1)
![image](https://github.com/meshery/meshery.io/assets/65087356/eaf5a690-9f83-44bc-91b7-b530670d9689)

2023-10-28 14:00 UTC, Lucif3r-in commented
> Can we have proper margin here as well, as we have in case of All and deployment. As we can see the item is touching to the technologies part on the left in the below cases here! ![image](https://user-images.githubusercontent.com/65087356/278814408-1e36814c-96d3-409e-a93d-eb8ee84e989e.png) ![image](https://user-images.githubusercontent.com/65087356/278814420-603cb17a-2fba-43da-b595-bd01dcae11f1.png) ![image](https://user-images.githubusercontent.com/65087356/278814436-eaf5a690-9f83-44bc-91b7-b530670d9689.png)

I can't find any breakpoint related code in `index.html` that defines the margin. Can you please point where the code for the page is? @abhijeetgauravm

2023-10-28 15:12 UTC, abhijeetgauravm reviewed
Looks good in preview now!

2023-10-29 07:33 UTC, abhijeetgauravm commented
Hey @Lucif3r-in Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-10-29 14:47 UTC, iArchitSharma approved these changes
@Lucif3r-in It looks really good now

2023-10-29 16:36 UTC, Lucif3r-in commented
> Hey @Lucif3r-in Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

Cool did that😊

2023-10-30 13:24 UTC, Lucif3r-in commented
@ritiksaxena124 I have done the suggested changes.
![image](https://github.com/meshery/meshery.io/assets/85403534/ae48a60f-4aeb-4533-8758-8f4d972e8461)

2023-10-30 13:47 UTC, Lucif3r-in commented
Done @ritiksaxena124 🚀🚀

2023-10-30 17:57 UTC, leecalcote commented
merge conflict…

2023-10-30 18:05 UTC, Lucif3r-in commented
Done @leecalcote 🚀🚀

2023-11-01 12:51 UTC, abhijeetgauravm commented
> Done @leecalcote 🚀🚀

@vishalvivekm @sudhanshutech @ritiksaxena124

2023-11-01 16:38 UTC, leecalcote commented
@Lucif3r-in this is a good feature to have.

2023-11-01 16:39 UTC, leecalcote commented
@Lucif3r-in do we have an open issue on search for the catalog? If not, do you mind opening one?

We can use https://lunrjs.com or similar.

2023-11-01 16:40 UTC, Lucif3r-in commented
> @Lucif3r-in do we have an open issue on search for the catalog? If not, do you mind opening one?
> 
> We can use https://lunrjs.com or similar.

Ya I was just about to write the same😅. Will surely open one issue about search

2023-11-03 09:39 UTC, Lucif3r-in commented
Can you please review this early as I have a related issue #1488 on which I am working on.

2023-11-04 17:23 UTC, sudhanshutech commented on Gemfile.lock
> +  x64-mingw-ucrt
@Lucif3r-in why this gemfile change?

2023-11-04 18:13 UTC, leecalcote commented
@Lucif3r-in what's the meaning behind your username? Is your intention to offend?

2023-11-04 18:18 UTC, Lucif3r-in commented
> @Lucif3r-in what's the meaning behind your username? Is your intention to offend?

Offend? I didn't get you 😅
I just had watched the Lucifer series and there were already usernames for simple Lucifer so...

2023-11-04 18:22 UTC, sudhanshutech commented
@Lucif3r-in merge conflict

2023-11-04 19:10 UTC, Lucif3r-in commented
@sudhanshutech can you please check now😊

2023-11-04 20:35 UTC, sudhanshutech commented
@Lucif3r-in the gemfile manages the dependencies of project we can't delete the file. You need to restage the gemfile changes from your pr(it could not be deleted, not change unless change in any dependencies)

2023-11-05 02:58 UTC, Lucif3r-in commented
Can anyone check and tell why am I getting a diff even if there is no change in Gemfile.lock

2023-11-05 04:05 UTC, iArchitSharma commented
@Lucif3r-in that's a common issue for all, you don't have to commit and push Gemfile.lock file

2023-11-05 04:07 UTC, Lucif3r-in commented
> @Lucif3r-in that's a common issue for all, you don't have to commit and push Gemfile.lock file

Now is the PR ok? or I have to do something else

2023-11-05 04:11 UTC, iArchitSharma commented
Remove the Gemfile.lock from PR

2023-11-05 04:47 UTC, closed without merging

2023-11-05 04:53 UTC, Lucif3r-in commented
I am a little confused with this rebasing and all, I will make a new PR