Added Recognition Page Link
meshery/meshery.io pull request #1529
Opened 2023-12-12 17:18 UTC by Raj100679

**Description**
Added Recognition link to community section

This PR fixes #1520 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-12 17:21 UTC, Raj100679 commented
@iArchitSharma @leecalcote , I haven't set the external : true in navigation.yml because it was not getting aligned properly, If there are any changes, you can let me know?

2023-12-12 18:25 UTC, iArchitSharma commented on .jekyll-metadata
**Do not push this file!**

2023-12-12 18:25 UTC, iArchitSharma commented on Gemfile.lock
**Do not push this file too!**

2023-12-12 18:32 UTC, iArchitSharma requested changes
Good work @Raj100679 

Can you please do these changes:
1. Can you please revert the changes made to configuration files, you don't have to push configuration files
2. In the header navigation please place the **Recognition** Link below _Mailing Lists_ and above _Discuss_

![image](https://github.com/meshery/meshery.io/assets/74408634/4e376826-b637-4556-b6a9-bb3e90226ea4)

2023-12-12 18:36 UTC, Raj100679 commented
@iArchitSharm I will do it tomorrow , I have to create a ppt for tomorrow

2023-12-13 14:56 UTC, iArchitSharma commented
@Raj100679 you there?

2023-12-13 14:59 UTC, Raj100679 commented
@iArchitSharma will raise a pr in some time

2023-12-13 15:24 UTC, closed without merging