bugfix: [Blog] Fix Blog Tags Responsiveness and
meshery/meshery.io pull request #1555
Opened 2023-12-21 17:42 UTC by horizenight

**Description**

This PR fixes #1551

**Notes for Reviewers**

[bugFix : [Blog] Overflowing Callout Card Border](https://github.com/meshery/meshery.io/commit/f1e0f2b89b414ada1f6431947a7eaac7a4ad52df) commit solves the overflow on [page](https://meshery.io/blog/unleashing-power-and-flexibility-the-synergy-of-rest-and-graphql-in-meshery)
<img width="461" alt="image" src="https://github.com/meshery/meshery.io/assets/76839614/1901397e-b12a-4fb9-853f-f1481e898a7f">

[bugFix : [Blog] Breaking CodeHighlight in Blog Article](https://github.com/meshery/meshery.io/commit/cdf81ee5bdc09a665731ee702ff4a94ceeaafb32) solves the breakage on this [page](https://meshery.io/blog/meshery-v06-release)
<img width="491" alt="image" src="https://github.com/meshery/meshery.io/assets/76839614/0c69b053-c99a-4c16-b210-e665f746794f">

[bugFix : [Blog] Fix Wierd Tag and Title OverFlow in Blog Articles](https://github.com/meshery/meshery.io/commit/99b2841e74540c023d65fdc6e4fefadc6c8ebbb9) solves the main tags issue 

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-22 11:59 UTC, ashutosh-rath02 commented
@horizenight The text size of tags is too small for mobile screens. Please check the design I have provided in the issue and try replicating it.
![image](https://github.com/meshery/meshery.io/assets/85403534/0294c7bd-6333-40f7-bab0-0ab9f76ddca8)

2023-12-22 12:13 UTC, ashutosh-rath02 requested changes

2023-12-22 12:13 UTC, ashutosh-rath02 commented on _sass/blog.scss
> +}
Instead try using `flex-column` and `flex-direction: column-reverse` for  `.blog-post .post-details` and `align-items: flex-start` for ` .post-date`  at smaller screens.

2023-12-22 12:13 UTC, ashutosh-rath02 commented on _sass/navigation.scss
> +}
You can remove these.

2023-12-22 12:13 UTC, ashutosh-rath02 commented on _sass/navigation.scss
> +		font-size: 0.6em;
Changing font-size should not be an option, please work this out.

2023-12-25 09:39 UTC, abhijeetgauravm commented
Hey @horizenight Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2023-12-25 10:11 UTC, horizenight commented
Hello @abhijeetgauravm 
I am travelling a lot this week, so it would be great if you have some design guidelines that will work on that : ) 
when available 👍🏼

2024-01-11 22:39 UTC, leecalcote commented
@horizenight are you still working on this?

2024-01-11 22:39 UTC, leecalcote commented
If not, @ashutosh-rath02, will you finish this off?

2024-01-14 19:40 UTC, leecalcote commented
@horizenight We'll consider this PR abandoned, yes?

2024-01-25 19:51 UTC, closed without merging

2024-01-25 19:51 UTC, sudhanshutech commented
@ashutosh-rath02 as you are taking care of this area and there is no response from @horizenight , we can close this one.
Thanks @horizenight will get you another issue when you are active