Pr 1555
meshery/meshery.io pull request #1577
Opened 2024-01-12 05:56 UTC by ashutosh-rath02

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-12 21:36 UTC, leecalcote commented
@iArchitSharma look good?

2024-01-13 17:01 UTC, iArchitSharma commented
@ashutosh-rath02 Can you please add a screenshot of your changes to help it move smoothly?

2024-01-14 09:58 UTC, ashutosh-rath02 commented
Before:
![image](https://github.com/meshery/meshery.io/assets/85403534/83a8d3e3-1394-4d4a-8598-776e720c5c28)

After:
![image](https://github.com/meshery/meshery.io/assets/85403534/442b9976-a5d9-43dc-b585-051604ad90f6)

@iArchitSharma Sorry for the delay.

2024-01-14 16:02 UTC, saurabh100ni commented
Hi @ashutosh-rath02  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-01-14 19:41 UTC, leecalcote requested changes
@ashutosh-rath02 will you remove any changes (like whitespace changes) that are not pertinent to this issue?

2024-01-15 09:44 UTC, vishalvivekm commented on _sass/blog.scss
> +      justify-self: flex-start;
```suggestion

```
No `justify-self` in flex. could be removed.

2024-01-15 09:45 UTC, vishalvivekm commented
@ashutosh-rath02 
post with authors: 
![Screen Shot 2024-01-15 at 15 13 41](https://github.com/meshery/meshery.io/assets/110674407/cc7423c8-0752-4a8b-b813-122f7ccf1e4b)

2024-01-15 09:48 UTC, vishalvivekm requested changes
Let's get feedback from other members of the community on call, in today's websites call.
I'll be adding this as an agenda item @ashutosh-rath02

2024-01-25 19:48 UTC, sudhanshutech commented
@ashutosh-rath02 

![image](https://github.com/meshery/meshery.io/assets/90546692/17c3be06-c95d-4426-8db4-229a99134d67)
![image](https://github.com/meshery/meshery.io/assets/90546692/9a0d7e3a-2e1a-4a91-8860-9499c75c207b)
![image](https://github.com/meshery/meshery.io/assets/90546692/8f2cd070-188c-43e7-84d8-9e6ff1979831)

2024-01-27 07:02 UTC, sudhanshutech commented
still working on it @ashutosh-rath02 ?

2024-01-27 07:07 UTC, ashutosh-rath02 commented
> still working on it @ashutosh-rath02 ?

Yes, will push commits by tomorrow 😊

2024-01-30 05:53 UTC, ashutosh-rath02 commented
@sudhanshutech i am unable to see the recent blog in my branch.

2024-01-30 06:24 UTC, ashutosh-rath02 commented
Closing this PR

2024-01-30 06:24 UTC, closed without merging