After image changed sucessufully
meshery/meshery.io pull request #1583
Opened 2024-01-14 19:06 UTC by surajvast1

**Description**

This PR fixes #1580 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

![image](https://github.com/meshery/meshery.io/assets/99933579/fcbd15af-5cc4-430b-ae2d-d8c59b558bf9)

2024-01-14 19:10 UTC, surajvast1 commented
Thanks for giving me this task. Let me know if anything changes—I'm here to help.

2024-01-14 19:20 UTC, leecalcote requested changes
Thanks. Try again. You've changed the Kuberentes blue to an off purple color. Retain the same coloring.

2024-01-15 06:23 UTC, surajvast1 commented
![image](https://github.com/meshery/meshery.io/assets/99933579/1b85b627-686d-4561-bae7-77cf83a1a506)

I believe the alternative image is much better.
  I belive this is much better image . 

The "before and after" button in the current code exhibits an issue: the "before" button doesn't hide properly after the slider is moved over, and there are functionality concerns when hovering from outside. Would you like me to address this within the current task, or a new issue will be created for it?

2024-01-15 11:42 UTC, vishalvivekm commented
@surajvast1
Today, we've our weekly Websites meeting at 6:30 PM IST : https://meet.layer5.io/websites.
Let's get feedback on your work in today's call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2024-01-16 04:17 UTC, surajvast1 commented
Hello @vishalvivekm and @leecalcote , I wanted to inform you that the image and container work for the issue is completed. If there's anything else I can assist with, please let me know. Otherwise, kindly consider merging this issue. Thank you!

2024-01-17 17:13 UTC, surajvast1 commented on images/gitops-snapshot.png
"As we discussed in the meeting, the reviews indicate that the image appears accurate. However, if you feel that adjustments are needed,  ill do it now thanks

2024-01-17 17:44 UTC, surajvast1 commented on images/gitops-snapshot.png
The given image isn't clear. I'll quickly fetch a new one and make the necessary updates.

2024-01-17 17:54 UTC, leecalcote commented on images/gitops-snapshot.png
The quality of it is crap. The coloration is off. And, the fact that you’re taking an entire screenshot is wrong as well.

2024-01-17 19:24 UTC, surajvast1 commented
![Uploading image.png…]()

2024-01-17 19:25 UTC, surajvast1 commented
![image](https://github.com/meshery/meshery.io/assets/99933579/fd5a8333-1fbb-4c97-9785-9e4c7436a8e6)

2024-01-17 19:26 UTC, surajvast1 commented
![image](https://github.com/meshery/meshery.io/assets/99933579/9f79999d-ef67-488f-9965-3b56e5f702ab)

2024-01-20 15:39 UTC, closed without merging