Enhanced the blog #1651
meshery/meshery.io pull request #1653
Opened 2024-03-05 16:24 UTC by Satakshijain

**Description**
Added the images and formatted the blog

This PR fixes #1651

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-03-10 20:55 UTC, vishalvivekm commented on assets/images/posts/2024-02-17-simplifying-cloud-infrastructure-and-kubernetes-management/meshery-catalog.png
Let's have a light-theme friendly image:
![image](https://github.com/meshery/meshery.io/assets/110674407/99074d47-1f3a-430c-b77f-6b07bc4529fa)

2024-03-10 20:57 UTC, vishalvivekm requested changes
Having images for dark as well as light theme would be great.

2024-03-13 10:40 UTC, sudhanshutech commented
@Satakshijain done?

2024-03-14 13:49 UTC, Satakshijain commented
Nope, I need a mockup of meshery-design for light theme

2024-03-16 13:41 UTC, sudhanshutech commented
> Nope, I need a mockup of meshery-design for light theme

you don't need a mockup, just had to grab a light and dark mode screenshot of same and apply some existing logic which just change the images based on theme here, just that

2024-03-20 01:23 UTC, merged