Implemented Meshery Brand Page
meshery/meshery.io pull request #1655
Opened 2024-03-10 01:13 UTC by shourya2002-geek

**Description**

This PR fixes #1537 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-03-10 08:18 UTC, ritiksaxena124 commented
1. Overflow issue @shourya2002-geek 
2. Use the same button component that we have on the site // @Rexford74 
3. On hover the section name should be highlighted in Caribbean green like other links on the site, remove this blue color
![image](https://github.com/meshery/meshery.io/assets/51539117/ea6f6f09-5239-4afc-8740-c8862cc00351)

2024-03-11 12:39 UTC, leecalcote requested changes

2024-03-11 13:11 UTC, vishalvivekm commented on _includes/brand-page.html
> +<style>
@shourya2002-geek https://github.com/meshery/meshery.io/pull/1084/files#diff-c33726049e0232971ee7180e61509a7888a11b2f32e7c46707e29c5a0b80c49d ^^

2024-03-17 20:29 UTC, vishalvivekm commented
@shourya2002-geek Hopefully, we're all done here?
Let's get some final feedback on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

2024-03-19 03:17 UTC, leecalcote requested changes

2024-03-19 03:17 UTC, leecalcote commented on _sass/rootvariables.scss
> -    --color-primary-light-dark:#d9e0e2;
@shourya2002-geek please remove all immaterial changes. These lines don't need to change and only make it difficult to review.

2024-03-19 03:18 UTC, leecalcote commented on .ruby-version
revert this change.

2024-03-19 03:18 UTC, leecalcote commented on _includes/brand-page.html
Don't use an "include". Just create a page.

Don't include a link to CSS. This will already be done in the heading.

2024-03-19 03:19 UTC, leecalcote commented on _includes/brand-page.html
> +  rel="stylesheet"
Remove these <link>s

2024-03-19 03:19 UTC, leecalcote commented on _includes/brand-page.html
> +  type="text/javascript"
Why do we need javascript on this page?

2024-03-19 03:20 UTC, leecalcote commented on assets/images/zoom.svg
This shouldn't be one image, but should be three images with text.

2024-03-19 03:20 UTC, leecalcote commented on assets/images/social-mobile.svg
text and images in different files.

2024-03-19 03:21 UTC, leecalcote commented
@shourya2002-geek this isn't working out.

@iArchitSharma, please help.

2024-03-23 10:14 UTC, iArchitSharma requested changes

2024-03-23 10:14 UTC, iArchitSharma commented on assets/images/social-mobile.svg
@Rexford74 Could you please provide individual images without text to @shourya2002-geek, the text can be directly added on the page instead of it being on image

2024-03-25 07:34 UTC, iArchitSharma commented
@shourya2002-geek you first removed `.jekyll-metadata` and `.rubyversion` and then you added it back again?
Please Remove!

2024-03-25 18:15 UTC, leecalcote requested changes
https://github.com/meshery/meshery.io/pull/1655/files#r1529632434

2024-03-26 22:12 UTC, merged