fix: page number in blog section is not in centre
meshery/meshery.io pull request #1687
Opened 2024-03-29 20:45 UTC by ShivamAhir

**Description**

This PR fixes #1686 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-03-31 18:55 UTC, vishalvivekm commented
@ShivamAhir Please consider updating this PR:
- sign off your commits 
- revert changes made to .jekyll-metadata
- resolve conflicts

Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

2024-04-01 02:39 UTC, sudhanshutech requested changes

2024-04-01 02:39 UTC, sudhanshutech commented on _sass/blog.scss
> +margin-left:-7em;
this doesn't look good giving negative value and in em. Please describe why? 
Add a screenshot

2024-04-04 16:45 UTC, sudhanshutech commented
@ShivamAhir still there?

2024-05-12 17:19 UTC, closed without merging