org & workspace switcher blog
meshery/meshery.io pull request #1740
Opened 2024-05-14 12:33 UTC by captain-Akshay

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-14 13:02 UTC, leecalcote requested changes

2024-05-14 13:02 UTC, leecalcote commented on collections/_posts/2024-05-14-organization-workspace-switcher.md
> +Meshery facilitates organization and workspace management, enabling diverse architectural spaces to thrive. Within the Layer5 Cloud ecosystem, organizations form the bedrock of multi-tenancy, while M
Please don't hyperlink the word "here". Instead, hyperlink the text that you're referring to.

2024-05-14 13:05 UTC, leecalcote commented on collections/_posts/2024-05-14-organization-workspace-switcher.md
> +- Switch to an organization where they have the required permissions.
```suggestion
- Switch to an organization where they have the required permissions.

Try Meshery's new organization and workspace switcher in the [Meshery Playground](https://play.meshery.io) and [let us know what you think](https://meshery.io/subscribe)!

```

@captain-Akshay "let us know what you think" could be a hyperlink to your blog post on the new Feedback component.

2024-05-14 13:05 UTC, leecalcote commented on collections/_posts/2024-05-14-organization-workspace-switcher.md
> +## Spaces
Change to Workspaces, please - in the heading and sentences below.

2024-05-17 10:06 UTC, ritiksaxena124 requested changes

2024-05-17 10:06 UTC, ritiksaxena124 commented on collections/_posts/2024-05-14-organization-workspace-switcher.md
> +Workspaces empower collaboration with your teams, enabling resource control and activity tracking. Organizations support multiple teams, with each team accommodating diverse users. Users have the fle
```suggestion
Workspaces empower collaboration with your teams, enabling resource control and activity tracking. Workspaces support multiple teams, with each team accommodating diverse users. Users have the flexibility to join multiple teams and organizations, fostering fluidity and efficiency in workflow management.
```

2024-05-18 14:26 UTC, vishalvivekm commented
@captain-Akshay Thank you for your contribution.
Let's discuss this on Websites's call on Monday. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

2024-05-24 07:32 UTC, sudhanshutech commented
@captain-Akshay ready to publish?
Any new gifs or content needed to add?

2024-06-10 11:22 UTC, sudhanshutech commented
@captain-Akshay is this completed?

2024-06-18 20:15 UTC, leecalcote commented on assets/images/posts/2024-06-01-organization-workspace-switcher/org-workspace-meshmap.png
Nice graphic!

2024-06-27 19:14 UTC, sudhanshutech commented
@captain-Akshay is this completed?

2024-07-01 09:52 UTC, Deepak0320Singhal commented
@captain-Akshay Thank you for your contribution.
Let's discuss this on Websites's call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

2024-09-05 12:41 UTC, closed without merging