Changed The Background color in choose your platform section
meshery/meshery.io pull request #1747
Opened 2024-05-17 19:43 UTC by shailpujan88

**Description**

This PR fixes #1735

**Notes for Reviewers**
Changed the background color of the Choose Your Platform section.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-05-17 19:50 UTC, shailpujan88 commented
![image](https://github.com/meshery/meshery.io/assets/114280481/e6848cfd-dd1f-4d0f-b6c1-3cf0d8f4820e)
@leecalcote I have made the required changes. Can you please verify them?

2024-05-18 08:01 UTC, ritiksaxena124 requested changes

2024-05-18 08:01 UTC, ritiksaxena124 commented on Gemfile.lock
Don't push `Gemfile.lock` file. Revert this change

2024-05-18 08:01 UTC, ritiksaxena124 commented on _includes/getting-started.html
> +      <div id="docker_code" class="toggle hideDiv" style="background-color: rgb(84, 89, 91);">
Don't use hardcoded values for styling. Try to use variables and avoid using inline-styling.

2024-05-18 08:01 UTC, ritiksaxena124 commented on _includes/getting-started.html
> +      <div id="brew_code" class="toggle hideDiv" style="background-color: rgb(84, 89, 91);">
Here as well.

2024-05-18 08:01 UTC, ritiksaxena124 commented on _includes/getting-started.html
> +      <div id="k8s-instructions_code" class="toggle hideDiv" style="background-color: rgb(84, 89, 91);">
Same

2024-05-18 08:01 UTC, ritiksaxena124 commented
Don't use hardcoded values for styling. Try to use variables and avoid using inline styling @shailpujan88.

2024-05-18 12:40 UTC, closed without merging