Fix: Button Overlap Issue in Responsive Design for Screen Widths Belo…
meshery/meshery.io pull request #1823
Opened 2024-07-14 06:11 UTC by rahulrana701

…w 767px/signoff

 Button is fully visible, not covered by any images in [Infrastructure directly in your PRs ] section at home page. , on screens below 767px.

This PR fixes #1822

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-07-17 18:39 UTC, Ashparshp reviewed
Thank you for your contribution. Please avoid mixing formatting changes with functional updates, as it makes reviews harder. If you can fix this, please do so as well.

2024-07-21 14:02 UTC, leecalcote commented
> Thank you for your contribution. Please avoid mixing formatting changes with functional updates, as it makes reviews harder. If you can fix this, please do so as well.

Thanks for this, @Ashparshp

2024-08-07 20:47 UTC, sudhanshutech requested changes

2024-08-07 20:47 UTC, sudhanshutech commented on _sass/features.scss
>  .features {
@rahulrana701 will you please remove the unnecessary line changes or fix this lint changes. Its hard to see what is the real change.

2024-08-08 04:13 UTC, Ashparshp commented
@sudhanshutech We're closing this PR and proceeding with another created by @amitamrutiya since we haven't heard back from @rahulrana701 for a month. Let's close this PR and move forward with the new one. Thanks, @rahulrana701.

2024-08-08 04:13 UTC, closed without merging

2024-08-08 11:26 UTC, rahulrana701 commented
I apologize for the recent delay. I have been dealing with health issues for the past week and a half, and the intense placement process has kept me very busy with college commitments. I assure you that I will prioritize and complete all assigned work moving forward. This PR was not up to standard because my Git was facing some issues at that moment, which affected its quality. I am committed to delivering higher-quality work from now on. Thank you for your understanding.