Add search (filter) for an specific Integration on Homepage's Integrations section
meshery/meshery.io pull request #1829
Opened 2024-07-27 19:21 UTC by shubhusion

**Description**

This PR fixes #1798

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-07-29 19:41 UTC, leecalcote commented
@hargunkaur286 you might offer review.

2024-07-31 11:00 UTC, hargunkaur286 reviewed
@shubhusion Can you share screenshots of the changes?
The images are missing in the deploy preview
<img width="1470" alt="Screenshot 2024-07-31 at 4 29 54 PM" src="https://github.com/user-attachments/assets/ed36c871-3ace-4da4-a964-04cfed36128a">

2024-07-31 11:13 UTC, shubhusion commented
> @shubhusion Can you share screenshots of the changes? The images are missing in the deploy preview <img alt="Screenshot 2024-07-31 at 4 29 54 PM" width="1470" src="https://private-user-images.githubusercontent.com/96698544/353804970-ed36c871-3ace-4da4-a964-04cfed36128a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQ1NTYsIm5iZiI6MTcyMjQyNDI1NiwicGF0aCI6Ii85NjY5ODU0NC8zNTM4MDQ5NzAtZWQzNmM4NzEtM2FjZS00ZGE0LWE5NjQtMDRjZmVkMzYxMjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZjRhY2EwNGI5MmZmNmU5MGY2YTNlYjMyMzgyMjE5ZDJmNjgxMTZjZmViYzUxNjEzYjUxNDI5MjhmNjM4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCp-ctbn0PiEZ-ppK4dj4fGb09pxN4cxk9RHefVtOhI">

@hargunkaur286 I have only added the search filter present above the images 

![image](https://github.com/user-attachments/assets/0ef2ec31-59b7-400a-afff-52326e819fa3)

2024-07-31 11:55 UTC, hargunkaur286 commented
> > @shubhusion Can you share screenshots of the changes? The images are missing in the deploy preview <img alt="Screenshot 2024-07-31 at 4 29 54 PM" width="1470" src="https://private-user-images.githubusercontent.com/96698544/353804970-ed36c871-3ace-4da4-a964-04cfed36128a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQ1NTYsIm5iZiI6MTcyMjQyNDI1NiwicGF0aCI6Ii85NjY5ODU0NC8zNTM4MDQ5NzAtZWQzNmM4NzEtM2FjZS00ZGE0LWE5NjQtMDRjZmVkMzYxMjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZjRhY2EwNGI5MmZmNmU5MGY2YTNlYjMyMzgyMjE5ZDJmNjgxMTZjZmViYzUxNjEzYjUxNDI5MjhmNjM4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCp-ctbn0PiEZ-ppK4dj4fGb09pxN4cxk9RHefVtOhI">
> 
> @hargunkaur286 I have only added the search filter present above the images
> 
> ![image](https://private-user-images.githubusercontent.com/96301987/353808459-0ef2ec31-59b7-400a-afff-52326e819fa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY4MzAsIm5iZiI6MTcyMjQyNjUzMCwicGF0aCI6Ii85NjMwMTk4Ny8zNTM4MDg0NTktMGVmMmVjMzEtNTliNy00MDBhLWFmZmYtNTIzMjZlODE5ZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExNDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZjRkZjEzNGUxYzYyMTI0ZTdlNGZlZTUyM2NjMjc1MTAwNmRmNzJjODRmMmJkMGI1ODg4ZTE3OGUyMzI2ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2oxKg1gv7qnT6FDH5lsd8CYqO-PS9nLZxjmxFcKU0Mw)

okay, can you share a full screenshot please

2024-07-31 11:57 UTC, hargunkaur286 requested changes

2024-07-31 11:57 UTC, hargunkaur286 commented on _includes/partials/homePage-integrations.html
> +                  <img src="${item.color}" loading="lazy" id="logo-dark-light"
I see the error, you have to call the icon's url here in the image tag, how are you calling 'item.color' in <img> tag? this is causing the issue of images not getting displayed.

2024-07-31 12:49 UTC, closed without merging

2024-07-31 13:05 UTC, shubhusion commented
Hi @hargunkaur286,

I have made the necessary changes. However, while rebasing, I commited an error that caused the commits of other collaborators to merge into this PR. So, I have closed this PR and created a new one.

Could you please review the new PR? Thanks!

PR: https://github.com/meshery/meshery.io/pull/1837