fix: broken link issue on perfomance management
meshery/meshery.io pull request #1845
Opened 2024-08-03 13:46 UTC by amitamrutiya

**Description**
Remove broken link and add valid once

This PR fixes #1841 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-08-03 17:02 UTC, Ashparshp commented
@amitamrutiya Please add this too the meeting minutes!

2024-08-07 20:39 UTC, sudhanshutech requested changes

2024-08-07 20:39 UTC, sudhanshutech commented on collections/_pages/features.html
> +      link: https://docs.meshery.io/guides/performance-management/performance-management
use this one please
```suggestion
      link: https://docs.meshery.io/guides/performance-management/managing-performance
```

2024-08-08 05:00 UTC, sudhanshutech approved these changes

2024-08-08 05:01 UTC, merged