implemented two column layout for footer in mobile view
meshery/meshery.io pull request #1946
Opened 2024-10-31 15:22 UTC by snehaio

**Description**

This PR fixes #1827

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-10-31 20:20 UTC, leecalcote commented
Thanks, @snehaio !

2024-11-01 19:34 UTC, snehaio commented
Noted! @GaganpreetKaurKalsi @Pratik-050 . 
Will work upon the same and update the pr shortly.

2024-11-02 20:52 UTC, snehaio commented
Rearranged the columns according to their structural similarity, as provided in the screenshot by @GaganpreetKaurKalsi . Please review it once and lmk if any changes are still required. Thankyou!

2024-11-03 05:28 UTC, GaganpreetKaurKalsi reviewed
Can we align the content as shown below? Try to use grid layout if flexbox isn't working for the requirement. @snehaio 

![image](https://github.com/user-attachments/assets/794fd092-3f04-4951-acf9-2e2a617ce66d)

2024-11-03 11:21 UTC, snehaio commented
Thank you, @GaganpreetKaurKalsi, for suggesting the grid layout! Switching to grid made it much easier to align the columns as needed. I’ve made the changes and updated the PR.

2024-11-03 15:41 UTC, vishalvivekm commented
@snehaio Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

2024-11-03 17:21 UTC, GaganpreetKaurKalsi requested changes
@snehaio there is this horizontal overflow on small screen size (look at the scrollbar at the bottom)
![image](https://github.com/user-attachments/assets/3d85d7b1-53e4-4a04-b60e-998a6135949e)

2024-11-04 11:14 UTC, vishalvivekm requested changes
@snehaio  revert the lint changes, if you would, please.

2024-11-04 11:20 UTC, vishalvivekm commented on _includes/footer.html
> +  </script>
any reasons to remove other breakpoints ? @snehaio 

<img src="https://github.com/user-attachments/assets/fe678cbc-d650-41b8-9317-803ceb63c7ca" width="300px" height="666px" />

2024-11-04 11:21 UTC, vishalvivekm commented
> @snehaio Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

Added this to agenda items: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0

2024-11-04 11:30 UTC, vishalvivekm commented on _includes/footer.html
> +	let toggleBtn = document.getElementById("mode-toggle-btn");
@snehaio we'd probably want to have the logic back in place here

2024-11-15 17:26 UTC, Pratik-050 commented on _includes/footer.html
> +	}
Please correct the formatting and confirm if the added logic is same as previous. Thanks!

2025-01-04 13:44 UTC, closed without merging