updated _includes/getting-stareted.html
meshery/meshery.io pull request #520
Opened 2021-08-20 08:15 UTC by ANURAG-PATHAK

Signed-off-by: ANURAG-PATHAK <pathakanurag605@gmail.com>

**Description**

This PR fixes #517 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-20 09:24 UTC, NikhilSharma03 approved these changes
LGTM :+1:

2021-08-21 02:10 UTC, warunicorn19 approved these changes
@ANURAG-PATHAK changes LGTM🎉! Just something to keep in mind for next time, if you could please make seperate PRs for seperate issues, putting everything together in one PR makes it difficult to the review the code. 

Also, Thanks for these changes, good work 😃.

2021-08-21 02:18 UTC, ANURAG-PATHAK commented
> @ANURAG-PATHAK changes LGTM🎉! Just something to keep in mind for next time, if you could please make seperate PRs for seperate issues, putting everything together in one PR makes it difficult to the review the code.
> 
> Also, Thanks for these changes, good work 😃.

Sure, I will take care of it next time, and thank you for your help and guidance.

2021-08-22 06:37 UTC, Jashpatel1 reviewed
Looks good. One more change if @leecalcote can confirm. Do we change the program name from CommunityBridge to LFX on the programs page as well?

2021-08-22 06:39 UTC, warunicorn19 commented
@Jashpatel1 if I'm not wrong, aren't we looking for new designs for that page?

2021-08-22 06:40 UTC, ANURAG-PATHAK commented
> Looks good. One more change if @leecalcote can confirm. Do we change the program name from CommunityBridge to LFX on the programs page as well?
<img width="1418" alt="Screenshot 2021-08-22 at 11 06 00 AM" src="https://user-images.githubusercontent.com/81188792/130345201-82134234-032d-4d70-a0e1-f154eb3d7890.png">

I was thinking the same but @warunicorn19 told that they will be redesigning the whole page

2021-08-22 06:47 UTC, ANURAG-PATHAK commented
I would have to commit a change because I deleted the community bridge icon so if my pr will be merged the site will look like this 
<img width="1440" alt="Screenshot 2021-08-22 at 12 16 56 PM" src="https://user-images.githubusercontent.com/81188792/130345423-cf4f3940-0925-4195-8ab3-7b84faf5b3b6.png">

that is why I think I should make this LFX then we can think of redesigning  the page as well so should I commit the change in this pr please approve

2021-08-22 07:13 UTC, ANURAG-PATHAK commented
<img width="1440" alt="Screenshot 2021-08-22 at 12 42 19 PM" src="https://user-images.githubusercontent.com/81188792/130346039-8302ed3d-8213-472a-893e-8c2ca745170e.png">



**this would be the new look after my commit**
should I make a commit for the same? 
@warunicorn19 @Jashpatel1

2021-08-24 17:26 UTC, leecalcote commented
@ANURAG-PATHAK a request: the white versions of these logos are terribly unattractive. Do you mind finding SVGs of each with color, so that we can assess whether shifting to colorized version is a bit more aesthetically pleasing?

2021-08-24 17:31 UTC, warunicorn19 commented
Maybe we could try using something like https://iconscout.com/icon/linux-foundation-3521550

2021-08-24 19:42 UTC, ANURAG-PATHAK commented
> @ANURAG-PATHAK a request: the white versions of these logos are terribly unattractive. Do you mind finding SVGs of each with color, so that we can assess whether shifting to colorized version is a bit more aesthetically pleasing?

Yes I can make a prototype using coloured SVGs, but I think we need to redesign this whole page as these large icons are making it a bit unattractive .

2021-08-24 20:34 UTC, ANURAG-PATHAK commented
@leecalcote , These are the updated changes 


<img width="1425" alt="Screenshot 2021-08-25 at 2 02 07 AM" src="https://user-images.githubusercontent.com/81188792/130686026-47a74f1f-7348-4bfd-ac98-b2a523382bde.png">









<img width="1405" alt="Screenshot 2021-08-25 at 2 02 35 AM" src="https://user-images.githubusercontent.com/81188792/130686041-84950e8f-b14c-4478-8432-b96268339dcd.png">

2021-08-24 20:36 UTC, leecalcote commented
@ANURAG-PATHAK thanks. That's not the MLH logo, no?

2021-08-24 20:38 UTC, ANURAG-PATHAK commented
> @ANURAG-PATHAK thanks. That's not the MLH logo, no?

there are two logos one is for mlh and other is of mlh fellowship

2021-08-31 02:38 UTC, leecalcote commented
Thanks, @ANURAG-PATHAK. Almost there?

2021-08-31 02:40 UTC, ANURAG-PATHAK commented
> Thanks, @ANURAG-PATHAK. Almost there?
yes, tell me if I need to change anything else

2021-08-31 02:42 UTC, ANURAG-PATHAK commented
> Thanks, @ANURAG-PATHAK. Almost there?

so which logo you want on the website mlh one or mlh-fellowship one

2021-09-02 05:01 UTC, warunicorn19 commented
@ANURAG-PATHAK the fellowship one works for now, also if you get rid of the merge conflict.

2021-09-02 09:07 UTC, warunicorn19 commented
@ANURAG-PATHAK could you please put in the LFX one as well?

2021-09-02 09:07 UTC, warunicorn19 commented
@Jashpatel1 should we go with the coloured ones?

2021-09-02 09:28 UTC, ANURAG-PATHAK commented
> @ANURAG-PATHAK could you please put in the LFX one as well?

sorry @warunicorn19 what LFX ? please elaborate 😊

2021-09-02 09:33 UTC, warunicorn19 commented
<img width="1440" alt="Screenshot 2021-09-02 at 3 00 02 PM" src="https://user-images.githubusercontent.com/53532328/131820196-f835cd16-56c3-418f-853b-d45670f3015a.png">

2021-09-02 09:36 UTC, ANURAG-PATHAK commented
so if you can confirm I can push the changes with coloured logo and LFX also or should I go with this one?

2021-09-02 13:46 UTC, leecalcote commented
Pulling in the big gun, @Nikhil-Ladha here.

2021-09-02 14:58 UTC, Nikhil-Ladha requested changes
Make a commit with the colored logos.
Change `Community Bridge` to `LFX` and also update the filename such that the page path reflects the same.
Use the MLH same as used [here](https://layer5.io/careers/programs).

2021-09-02 14:58 UTC, Nikhil-Ladha commented on .idea/.gitignore
> +# Default ignored files
Remove all the `.idea` files from the commit.

2021-09-03 07:36 UTC, ANURAG-PATHAK commented
due to some errors, I pulled another PR #544 
sorry for the inconvenience 😔😔

2021-09-03 10:44 UTC, Nikhil-Ladha commented
Closing this PR based on the above comment.

2021-09-03 10:44 UTC, closed without merging