added callouts
meshery/meshery.io pull request #525
Opened 2021-08-25 18:24 UTC by debo19

Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
Added callouts to various resources in place of the list present previously.
This PR fixes #524 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-28 21:10 UTC, warunicorn19 requested changes
![Screenshot_20210829-023856](https://user-images.githubusercontent.com/53532328/131231080-6f58032c-8af6-4866-a679-511e9665d272.jpg)

Looks great!, But a little too big for mobile view, could we get it a little smaller.?

2021-08-29 13:39 UTC, warunicorn19 submitted a review, later dismissed
LGTM 🎉, thanks @debo19

2021-08-30 12:11 UTC, Tanuj22 submitted a review, later dismissed
LGTM

2021-08-30 12:24 UTC, Nikhil-Ladha requested changes

2021-08-30 12:24 UTC, Nikhil-Ladha commented on _includes/partials/callouts.html
> +      </div>
Considering you are already adding the icon using CSS just above this line.
I don think we need the image being added separately. The same is applicable for the code below.

2021-08-30 23:12 UTC, leecalcote commented
A small nitpick: is it possible have all of the cards of equal height (size)?

2021-08-30 23:12 UTC, leecalcote approved these changes

2021-08-31 05:50 UTC, debo19 commented
![cards](https://user-images.githubusercontent.com/85789734/131448742-7531356b-3daa-4095-a6b9-51c0f4847560.jpg)
@leecalcote  They seem to have the same height for me, is it different for you?

2021-08-31 05:52 UTC, warunicorn19 commented
<img width="1440" alt="Screenshot 2021-08-31 at 11 21 11 AM" src="https://user-images.githubusercontent.com/53532328/131449303-a98fb181-8832-473b-84c3-398b630e11e6.png">

safari doing it's thing again.

2021-08-31 18:56 UTC, leecalcote commented on _includes/partials/callouts.html
> +    <p class="small">Watch community meeting recordings on our youtube channel</p>
```suggestion
    <p class="small">Watch community meeting recordings on our YouTube channel</p>
```

2021-08-31 18:56 UTC, leecalcote commented on _includes/partials/callouts.html
> +   <a class="card1" href="https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA">
YouTube links need to include the subscription confirmation. 

```suggestion
   <a class="card1" href="https://www.youtube.com/c/Layer5io?sub_confirmation=1">
```

2021-08-31 18:56 UTC, leecalcote commented on _sass/landing-page.scss
> +    content: url('../images/logos/meshery-logo.png');
As a general rule, let's prefer SVGs to PNGs.

2021-08-31 19:03 UTC, leecalcote approved these changes
Thank you, @debo19. 🥇

2021-08-31 19:03 UTC, merged