Mailing lists updated.
meshery/meshery.io pull request #535
Opened 2021-08-27 14:03 UTC by Zain-Muiz

Signed-off-by: Zain-Muiz <zainu10863@gmail.com>

**Description**

Have listed following mailing lists on meshery.io:

| Meshery Developers | dev-group@meshery.io |
| Meshery Users | user-group@meshery.io |
| Meshery Maintainers | maintainers@meshery.io |
| Meshery Security and Vulnerability Reports | meshery-security-vulns-reports@meshery.dev |
| Meshery Community | community@meshery.io |

This PR fixes #518 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-29 13:29 UTC, warunicorn19 requested changes
hey @Zain-Muiz, this behavior is happening because of the hard-coding, could you please remove most of that and think of some other way to do this? One way to try could be, keeping the size of the fields fixed and then just wrap it in a smaller view.

2021-08-31 19:26 UTC, Zain-Muiz commented
@warunicorn19 Ping !

2021-08-31 19:41 UTC, warunicorn19 requested changes
@Zain-Muiz good stuff, just a little nitpick, could you please just put all the inline styling into the stylesheet.

2021-08-31 19:43 UTC, warunicorn19 requested changes

2021-08-31 19:43 UTC, warunicorn19 commented on _includes/mailing-lists.html
> +            flex--alijgn-center
```suggestion
            flex--align-center
```

2021-09-01 07:05 UTC, Nikhil-Ladha commented
Agreed @warunicorn19 !
@Zain-Muiz if I understand correctly, you gave the class names based on bootstrap styles but unfortunately we don't use bootstrap on our sites, so the class names don't make sense here. Please use a single class and define all the styles within it, which includes: `flex, alignment, background-color` and so on...
Also, since we are also using the same `Mailing-Lists` HTML as a section on the bottom of the home page,  the styles in that are also affected due to these changes. Please fix them as well.

2021-09-03 13:49 UTC, Zain-Muiz commented
Heyy @Nikhil-Ladha @warunicorn19 , I have fixed as both of you suggested. @Nikhil-Ladha , theres a small concern though. Given the design of the mailing list, I feel it is bit big to be on our home page. Anyway, If time permits, I'll share this on the community call.

2021-09-03 13:52 UTC, Nikhil-Ladha commented
> Heyy @Nikhil-Ladha @warunicorn19 , I have fixed as both of you suggested. @Nikhil-Ladha , theres a small concern though. Given the design of the mailing list, I feel it is bit big to be on our home page. Anyway, If time permits, I'll share this on the community call.

Have you pushed the changes already? I can't seem to find the commit 🤔 .... I agree on the design part and I think it is a good item to be discussed on the Websites Call that we have every Monday instead of the Community Call.

2021-09-03 13:54 UTC, warunicorn19 commented
Yes let's talk about this on the websites' call 😊.

2021-09-03 14:11 UTC, Zain-Muiz commented
> > Heyy @Nikhil-Ladha @warunicorn19 , I have fixed as both of you suggested. @Nikhil-Ladha , theres a small concern though. Given the design of the mailing list, I feel it is bit big to be on our home page. Anyway, If time permits, I'll share this on the community call.
> 
> Have you pushed the changes already? I can't seem to find the commit 🤔 .... I agree on the design part and I think it is a good item to be discussed on the Websites Call that we have every Monday instead of the Community Call.

No I didnt commit, thought would ask before that! Yeah, right, Websites will be the right place, Lets keep it for monday ! Ill commit my changes in some time and ping both of you then. Maybe any of you can have a look, if you get time before that.

2021-09-04 13:59 UTC, Zain-Muiz commented
@warunicorn19 @Nikhil-Ladha .

P. S : will resolve conflicts once we come to a conclusion on the design :)

2021-09-09 19:10 UTC, Zain-Muiz commented
Ping ! @warunicorn19

2021-09-09 19:15 UTC, warunicorn19 approved these changes
Woohoo, good stuff @Zain-Muiz 🎉, thanks for seeing this to the end. LGTM✌️.

2021-09-09 19:23 UTC, Nikhil-Ladha approved these changes
Looks good!

2021-09-09 19:23 UTC, merged