Para and Image are now of same size and added hoverable buttons in th…
meshery/meshery.io pull request #537
Opened 2021-08-30 20:16 UTC by AnshumanDhiman

…e links within the paragraphs w/signoff

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

As discussed with lee I had removed the marquee and the color of slack icon is also set to default.
The paragraph and the supporting image will now occupy same space and instead of href links added hoverable buttons to them

This PR fixes #532 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-30 20:33 UTC, warunicorn19 requested changes
Could you please add the button to this too.

<img width="1098" alt="Screenshot 2021-08-31 at 2 00 17 AM" src="https://user-images.githubusercontent.com/53532328/131401576-76c3cd7e-2587-4b4f-8d01-b82de3f3d10b.png">

2021-08-30 20:33 UTC, warunicorn19 commented on index.html
> +					<a href="https://docs.meshery.io">See the service mesh patterns</a>
```suggestion
					<a href="https://docs.meshery.io/functionality/pattern-management">See the service mesh patterns</a>
```
Let's change the link to this.

2021-08-30 23:06 UTC, leecalcote commented
@AnshumanDhiman heads-up: it's always good to ensure that an issue is approved by a maintainer before implementing.

Feedback:

- The buttons are too close to their description
- There's missing whitespace between "(SMP)" and the text before it.
- "See the testing SMI conformance" is grammatically incorrect.
- Not all of the other sections have buttons added. Let's be consistent with either using buttons or not using them.

2021-08-30 23:14 UTC, leecalcote commented
@AnshumanDhiman I think very well of your efforts here. Please keep it up.

2021-08-31 08:25 UTC, AnshumanDhiman commented
Thanks @leecalcote every PR that I generate gives me more confidence and enthusiasm towards contributing to the layer5 community😀

2021-08-31 08:31 UTC, AnshumanDhiman commented
> @AnshumanDhiman heads-up: it's always good to ensure that an issue is approved by a maintainer before implementing.
> 
> Feedback:
> 
> * The buttons are too close to their description
> * There's missing whitespace between "(SMP)" and the text before it.
> * "See the testing SMI conformance" is grammatically incorrect.
> * Not all of the other sections have buttons added. Let's be consistent with either using buttons or not using them.

What I think is that the buttons gives the visitor and the website a better way to interact with each other😅

2021-08-31 19:06 UTC, leecalcote commented
> > @AnshumanDhiman heads-up: it's always good to ensure that an issue is approved by a maintainer before implementing.
> > Feedback:
> > 
> > * The buttons are too close to their description
> > * There's missing whitespace between "(SMP)" and the text before it.
> > * "See the testing SMI conformance" is grammatically incorrect.
> > * Not all of the other sections have buttons added. Let's be consistent with either using buttons or not using them.
> 
> What I think is that the buttons gives the visitor and the website a better way to interact with each other😅

I agree. The buttons are an improvement. 👍 We need to give them a little breathing room from the text above them, though.

2021-08-31 19:07 UTC, leecalcote commented
...and you did just that. Nice!

We'll have to think of other appropriate links to have as buttons for the other sections. Thanks for this, @AnshumanDhiman 💯

2021-08-31 19:07 UTC, leecalcote approved these changes

2021-08-31 19:07 UTC, merged