[Readme Docs] Added Ruby installation note to Readme
meshery/meshery.io pull request #554
Opened 2021-09-12 18:49 UTC by Zain-Muiz

Signed-off-by: Zain-Muiz <zainu10863@gmail.com>

**Description**

Added Installation note while installing ruby as beginners often tend to install the latest version of Ruby. ( which is different from that mentioned in Gemfile )

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-09-12 18:57 UTC, warunicorn19 requested changes

2021-09-12 18:57 UTC, warunicorn19 commented on README.md
> +- First [install Ruby](https://jekyllrb.com/docs/installation/), then install Jekyll and Bundler. ( **Note** : Install the same version of ruby as mentioned in the [Gemfile](https://github.com/mesher
```suggestion
- First [install Ruby](https://jekyllrb.com/docs/installation/), then install Jekyll and Bundler. ( **Note** : Install the same version of ruby as mentioned in the [Gemfile](https://github.com/meshery/meshery.io/blob/master/Gemfile) )
```
Consider this instead.

2021-09-12 18:58 UTC, Zain-Muiz commented on README.md
> +- First [install Ruby](https://jekyllrb.com/docs/installation/), then install Jekyll and Bundler. ( **Note** : Install the same version of ruby as mentioned in the [Gemfile](https://github.com/mesher
Gotchya ! Alright !

2021-09-12 19:03 UTC, Zain-Muiz commented
@warunicorn19 Done !

2021-09-12 19:12 UTC, warunicorn19 approved these changes
LGTM 🎉, Thanks @Zain-Muiz

2021-09-14 06:10 UTC, leecalcote approved these changes

2021-09-14 06:10 UTC, merged