Fix UI Alignment for copy to clipboard
meshery/meshery.io pull request #612
Opened 2021-11-12 14:57 UTC by sidecodes

Signed-off-by: Mohd Talha <mohmmad.talha@outlook.com>

**Description**

This PR fixes #611

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

![ui-alignment](https://user-images.githubusercontent.com/13354987/141486864-a670c48e-46c8-4ded-9a66-5f08c86c97e3.gif)

2021-11-12 16:00 UTC, warunicorn19 requested changes
@sidecodes a better approach would be to increase the z-index, this is not looking that good

2021-11-12 16:11 UTC, sidecodes commented
> Thank you@sidecodes for the PR, a better approach would be to increase the z-index, this is not looking that good

Sure I will change it as requested.

2021-11-12 16:12 UTC, warunicorn19 commented
Thank you sir.

2021-11-13 14:04 UTC, warunicorn19 commented on _includes/getting-started.html
> +                    <span class="tooltiptext" style="font-size: 15px; width: 140px; height: 40px; padding: 0; line-height: 40px; top: 2.5rem; left: -70px;">Copy to clipboard</span>
```suggestion
                    <span class="tooltiptext" style="font-size: 15px; width: 140px; height: 40px; padding: 0; line-height: 40px; top: 2rem; left: -80px;">Copy to clipboard</span>
```

2021-11-13 17:14 UTC, sidecodes commented on _includes/getting-started.html
> +                    <span class="tooltiptext" style="font-size: 15px; width: 140px; height: 40px; padding: 0; line-height: 40px; top: 2.5rem; left: -70px;">Copy to clipboard</span>
Updated as suggested. Please have a look. @warunicorn19 

![updated-ui-alignment](https://user-images.githubusercontent.com/13354987/141652792-dffe63cc-c71e-43c0-b77a-2086bb0b0893.gif)

2021-11-14 15:00 UTC, warunicorn19 commented
@sidecodes you seem to have forgotten to make the changes on a couple😅, like KinD, Helm, etc. could you please take a look and make the tooltip consistent on all the snippets

2021-11-14 15:55 UTC, sidecodes commented
> 
> 
> @sidecodes you seem to have forgotten to make the changes on a couple😅, like KinD, Helm, etc. could you please take a look and make the tooltip consistent on all the snippets, they should be in the same position in all.

Changed it for consistency. @warunicorn19  
![updated-ui-alignment-2](https://user-images.githubusercontent.com/13354987/141688317-ae9501f1-5fa9-43b9-8800-28a9acc41556.gif)

2021-11-14 17:01 UTC, warunicorn19 approved these changes
Looking good! thank you @sidecodes for this to the end.😄

2021-11-14 17:02 UTC, merged