Meshery adapters for NGINX, Cilium, and Traefik moved to stable
meshery/meshery.io pull request #714
Opened 2022-05-14 04:13 UTC by karnatisrinivas

Meshery adapters for NGINX, Cilium, and Traefik status moved to stable

Signed-off-by: Srinivas karnati <karnatisrinivasulareddy@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-05-15 05:19 UTC, Akshit42-hue requested changes
LGTM, It would be great if you update the docs as well @karnatisrinivas

2022-05-15 05:37 UTC, karnatisrinivas commented
Hello @Akshit42-hue  , I made changes to docs. Here's the PR: https://github.com/meshery/meshery/pull/5516 
Let me know if I missed anything

2022-05-19 11:15 UTC, YashKamboj approved these changes

2022-05-19 11:15 UTC, YashKamboj commented
LGTM!!!!

2022-05-19 11:54 UTC, merged