add spire and istio logo on card
meshery/meshery.io pull request #809
Opened 2022-08-22 13:46 UTC by mharshita

**Description**

This PR fixes #807

**Notes for Reviewers**
Added Spire and Istio logo on card on catalogue
<img width="294" alt="Screenshot 2022-08-22 at 7 16 11 PM" src="https://user-images.githubusercontent.com/60281688/185936334-5902557a-0d67-41ac-9baf-e41b280d9f86.png">

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-22 13:49 UTC, warunicorn19 requested changes
Ideally we want this to be one svg of the same size as other svgs, not doing that would lead to a lot of conditional statements and excess CSS.

2022-08-22 13:58 UTC, mharshita commented
@warunicorn19 So we need to keep spire logo or istio logo on card?

2022-08-22 14:01 UTC, leecalcote commented
@Revolyssup we list this design as Istio and SPIRE, which is what we really want in the catalog, but is this design SPIRE-only currently?

2022-08-22 14:43 UTC, Revolyssup commented
> @Revolyssup we list this design as Istio and SPIRE, which is what we really want in the catalog, but is this design SPIRE-only currently?

This design is called Istio-ready Spire because it is a basic spire pre-requisite installation after which we install Istio.

2022-08-22 17:12 UTC, mharshita commented
@Revolyssup I have pushed the changes
<img width="302" alt="Screenshot 2022-08-22 at 10 35 18 PM" src="https://user-images.githubusercontent.com/60281688/185979881-403add0d-e2ac-4504-9793-9433f52128bf.png">

2022-08-22 17:38 UTC, leecalcote commented
Thanks, @mharshita. If you can combine these SVGs into a single SVG image, then, we're all set.

2022-08-22 20:33 UTC, leecalcote commented
> Thanks, @mharshita. If you can combine these SVGs into a single SVG image, then, we're all set.

(not a PNG, pretty please, but an SVG)

2022-08-23 17:15 UTC, mharshita commented
I have pushed the changes. Please review again.
<img width="300" alt="Screenshot 2022-08-23 at 10 45 26 PM" src="https://user-images.githubusercontent.com/60281688/186222973-9efa1dc3-27eb-446b-ac93-8f010609d0c9.png">

2022-08-23 17:17 UTC, warunicorn19 commented
Umm, I think the istio logo is a little skewed.

2022-08-24 14:24 UTC, mharshita commented
I have pushed the changes. Please review again.

2022-08-24 14:59 UTC, mharshita commented on _sass/catalog.scss
> +      margin-left: 11%;
Images were looking a bit left aligned. I made this change to center align them.

2022-08-24 15:00 UTC, mharshita commented on _sass/catalog.scss
> +      margin-left: 11%;
This is how the images were looking previously.
<img width="858" alt="Screenshot 2022-08-24 at 8 29 54 PM" src="https://user-images.githubusercontent.com/60281688/186452567-9a4e6633-e171-45a0-9606-afbe7e7c7eb9.png">

2022-08-24 15:02 UTC, mharshita commented on _sass/catalog.scss
> +      margin-left: 11%;
After this change, they are looking like this.
<img width="844" alt="Screenshot 2022-08-24 at 8 31 54 PM" src="https://user-images.githubusercontent.com/60281688/186453072-18171e52-8122-4b72-a214-03a2096a6824.png">

2022-08-24 15:14 UTC, leecalcote commented on _sass/catalog.scss
> +      margin-left: 11%;
@mharshita, if this centering challenge is something that you would like to take on in another PR, that would work as well.

2022-08-24 18:19 UTC, mharshita commented on _sass/catalog.scss
> +      margin-left: 11%;
For centering the images, we can put image inside a div and for that div, we can set `display: flex` and `justify-content: center`. I have tried, this is working. Should I push these changes?

<img width="928" alt="Screenshot 2022-08-24 at 11 45 41 PM" src="https://user-images.githubusercontent.com/60281688/186493103-fc8be33e-a0ec-4b27-9505-dca32cfef060.png">

2022-08-24 18:20 UTC, leecalcote commented on _sass/catalog.scss
> +      margin-left: 11%;
Sounds about right to me. Unless one of the other reviewers suggests otherwise, yes, please proceed.

2022-08-24 18:28 UTC, mharshita commented on _sass/catalog.scss
> +      margin-left: 11%;
I have pushed the changes.

2022-08-25 00:48 UTC, leecalcote commented
Ample time given to the other reviewers to review...

Looks good to me, @mharshita. Let's merge.

2022-08-25 00:48 UTC, merged

2022-08-25 00:48 UTC, leecalcote commented
And there it is! 😄 Yay, @mharshita! 🎈