UPDATE/Lorem Ipsum on Catalog Pages
meshery/meshery.io pull request #816
Opened 2022-08-26 09:12 UTC by eeshaanSA

Signed-off-by: Eeshaan Sawant <eeshaans1@gmail.com>

**Description**
Fixed an error where the new wasm filters and some of the meshery pattern cards showed placeholder texts instead of relevant information.

This PR fixes #768 

**Notes for Reviewers**
Just removed the placeholder texts, I need more iformation on the exact information that needs to be put in. Please fill me on that.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-28 17:35 UTC, asubedy commented
@eeshaanSA you can fill `What does this pattern does?` section with information situated here. https://www.opensourceagenda.com/projects/wasm-filters

2022-08-29 03:52 UTC, eeshaanSA commented
sure.

2022-08-29 10:46 UTC, eeshaanSA commented
also, @asubedy, any idea what goes into the caveats and consideration section of these filters?

2022-08-29 10:47 UTC, eeshaanSA commented
Because as of now, I can see that some filters have the info filled, but the caveats and consideration part is still filled with filler text. 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/100678386/187184628-167be4b5-f72b-4e22-a29a-57fd29566b77.png">

2022-08-30 04:45 UTC, eeshaanSA commented
This was all the information I could find from those links, @asubedy. There are still some filters and patterns remaining.

2022-09-23 08:00 UTC, eeshaanSA commented
Can we have this information merged, atleast?

2022-09-23 08:44 UTC, asubedy requested changes

2022-09-23 08:44 UTC, asubedy commented on collections/_catalog/wasm/metrics-store.md
> -URL: "https://github.com/layer5io/wasm-filters/releases"
Please add the URL field back.

2022-09-26 09:37 UTC, eeshaanSA commented on collections/_catalog/wasm/metrics-store.md
> -URL: "https://github.com/layer5io/wasm-filters/releases"
aight.

2022-10-01 18:33 UTC, eeshaanSA commented
// @asubedy

2022-10-01 21:38 UTC, leecalcote approved these changes

2022-10-01 21:38 UTC, leecalcote commented
@eeshaanSA a few merge conflicts have popped up. Will address these?

2022-10-02 19:51 UTC, leecalcote requested changes
merge conflicts

2022-10-03 08:42 UTC, eeshaanSA commented
Will try to fix it asap.

2022-10-03 16:59 UTC, eeshaanSA commented
@leecalcote @asubedy  can you check?

2022-10-03 17:06 UTC, leecalcote approved these changes
LGTM

2022-10-03 17:06 UTC, merged