aligning the external link + header capitalised
meshery/meshery.io pull request #831
Opened 2022-09-01 05:17 UTC by legendarykamal

Signed-off-by: Kamal Nayan <95926324+legendarykamal@users.noreply.github.com>

**Description**

1> The external linked looked offset so -> aligned them 
2> changed the header on the home page 

Small changes but give more proffesional look.

This PR fixes #

**Notes for Reviewers**
Earlier:- 
![image](https://user-images.githubusercontent.com/95926324/187836908-8714db76-7641-43bc-b9c9-51ebefda2fdd.png)

Now:- 
![image](https://user-images.githubusercontent.com/95926324/187836730-ece3a4fc-746f-45d3-ad57-2f7dc0409d7d.png)

![image](https://user-images.githubusercontent.com/95926324/187836312-11b10e03-41ba-4593-b5e2-0f4b3a48d32e.png)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-09-01 09:17 UTC, leecalcote commented
The menus still overlap when one is opening and the other closing... or this is PR not addressing the issue that you picked up?

2022-09-01 11:35 UTC, legendarykamal commented
hi @leecalcote that issue has been solved in this PR https://github.com/meshery/meshery.io/pull/830 .

while this PR tries to achieve things mentioned in the desc which in 
1> The external links looked offset so -> aligned them
2> changed the header on the home page

2022-09-01 14:19 UTC, Rohith-Raju commented
@legendarykamal looks good other than that!!

2022-09-01 17:08 UTC, legendarykamal commented
> @legendarykamal looks good other than that!!

thanks @Rohith-Raju lets get this merged :smiley:

2022-09-15 16:54 UTC, leecalcote requested changes

2022-09-15 16:54 UTC, leecalcote commented on _includes/homePage.html
> +		<h1 style="margin: 3rem 0rem 3rem 0rem;">The <span style="font-weight: 300 !important">extensible</span> Kubernetes manager</h1>
Revert, please

2022-09-15 16:54 UTC, leecalcote commented on _includes/navigation.html
> +							style="max-width:  10px; vertical-align:center;" />
good

2022-09-15 17:09 UTC, legendarykamal commented on _includes/homePage.html
> +		<h1 style="margin: 3rem 0rem 3rem 0rem;">The <span style="font-weight: 300 !important">extensible</span> Kubernetes manager</h1>
Oh, so that was on purpose ok ok :+1:

2022-09-15 17:11 UTC, legendarykamal commented on _includes/navigation.html
> +							style="max-width:  10px; vertical-align:center;" />
:smile:

2022-10-01 21:33 UTC, leecalcote commented
Thanks for this, @legendarykamal. The superscript placement of the external link icons is intentional. Given that the both of the suggested changes in this PR are not desired, I'll close this PR.

2022-10-01 21:33 UTC, closed without merging