Bug Fixed
meshery/meshery.io pull request #864
Opened 2022-10-05 10:06 UTC by UtkarshMishra12

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**

This PR fixes #843 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-10-05 10:09 UTC, UtkarshMishra12 commented
I'm not able to upload the video for both before the update and after the update.
So may I upload it on the drive and paste the link here? @leecalcote @legendarykamal

2022-10-05 10:21 UTC, UtkarshMishra12 commented
Before Update - 
[Video](https://drive.google.com/file/d/1kchxaMR2mbfhkVXf-2FLc6d3qAZh2263/view?usp=sharing)

After Update - 
[Video](https://drive.google.com/file/d/1Y8hDEtKFX7-D7mE85oa9ckXH8xgGmlPs/view?usp=sharing)

2022-10-05 10:21 UTC, legendarykamal requested changes
good sleek @UtkarshMishra12 do this one change 👍

2022-10-05 10:21 UTC, legendarykamal commented on _includes/subscribe.html
> +  @media (min-width: 841px) and (max-width: 1210px) {
make it 1229px  ,a minor but still it caught my eye. 
![image](https://user-images.githubusercontent.com/95926324/194038161-bf26aa2c-95d9-417c-81fe-b81772e02538.png)

2022-10-05 10:28 UTC, UtkarshMishra12 commented
@legendarykamal Please check it now.

2022-10-06 17:40 UTC, UtkarshMishra12 commented
@legendarykamal  Gentle Reminder 😊

2022-10-06 17:42 UTC, legendarykamal approved these changes
sleek awesome good to go @UtkarshMishra12  🎸

2022-10-11 05:08 UTC, Krishna2323 commented
@UtkarshMishra12 I would suggest a change to your code.

Desc: The input box width is too small according to the width of subscribe btn (at 1229px).

Current behavior at 1229 :
![Screenshot 2022-10-11 103127](https://user-images.githubusercontent.com/85894871/195001503-4c57f822-ee69-4d4c-9fc7-30e176190eab.png)

Expected behavior:
![Screenshot 2022-10-11 103219](https://user-images.githubusercontent.com/85894871/195001579-2d1eb51f-58d3-4dc8-a94d-00a77bb004d1.png)

2022-10-11 12:41 UTC, Krishna2323 commented
Now it looks good to me and is ready to be merged.
@legendarykamal @leecalcote, correct me if I am wrong.

2022-10-11 12:50 UTC, legendarykamal approved these changes

2022-10-11 12:50 UTC, legendarykamal commented on _includes/subscribe.html
> +      width: 350px !important;
cherry on the cake 🍰

2022-10-13 16:31 UTC, Nikhil-Ladha requested changes
While you are there can you make the width of the "Project Mailing Lists" buttons consistent as well?
Also, make the width of the "subscribe" equal to the maximum width of the input field (not greater than that).

2022-10-13 17:43 UTC, asubedy approved these changes
LGTM 👍

2022-10-13 17:46 UTC, asubedy commented
Could you merge the master branch to your branch it seems, and also changes from @Nikhil-Ladha, other than that it looks good. 👍

2022-10-13 18:17 UTC, legendarykamal commented
@Nikhil-Ladha project mailing list buttons are being addressed in a separate issue and someone is working on it.

While subscribe button could be taken care of in this itself. // @UtkarshMishra12 .

2022-10-14 13:00 UTC, UtkarshMishra12 commented
@Nikhil-Ladha @legendarykamal @asubedy  Please review it now, the changes are made to the subscribe button.

2022-10-15 14:22 UTC, UtkarshMishra12 commented
Gentle reminder @Nikhil-Ladha 😊

2022-10-16 08:28 UTC, Nikhil-Ladha approved these changes

2022-10-16 08:28 UTC, merged