[Catalog] Text and Modal chip alignment colour fixed
meshery/meshery.io pull request #965
Opened 2023-01-13 08:38 UTC by MrBehl06

Signed-off-by: Sandeep Behl sandeepbhel05@gmail.com

**Description**

Current State
<img width="1025" alt="Screenshot 2023-01-13 at 14 06 03" src="https://user-images.githubusercontent.com/101118926/212275255-b175e4b2-2501-43db-8d93-9c7c2f6081ee.png">
<img width="1256" alt="Screenshot 2023-01-13 at 13 55 39" src="https://user-images.githubusercontent.com/101118926/212273465-514f54e0-9adc-449b-a761-b459350183aa.png">

Desired State :
<img width="916" alt="Screenshot 2023-01-13 at 13 58 45" src="https://user-images.githubusercontent.com/101118926/212273882-2559f064-a3a9-47df-abc2-f0d7482130ed.png">
<img width="867" alt="Screenshot 2023-01-13 at 14 00 55" src="https://user-images.githubusercontent.com/101118926/212274198-f948fc73-f584-4ea5-8289-b44a22183045.png">

This PR fixes #
These are the following issues fixed in this PR:
1)Text colour and aligned fixed of the modal name.
2)Modal-pattern-image aligned with the text.
3)Modal-chip aligned and colour fixed.
4)em, strong, span colours set according to night mode and dark mode 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-01-13 08:39 UTC, MrBehl06 commented
@GaganpreetKaurKalsi @leecalcote Please the changes.

2023-01-13 17:36 UTC, GaganpreetKaurKalsi submitted a review, later dismissed
Looks good 👍 Great job 💯

2023-01-16 08:24 UTC, MrBehl06 commented
@leecalcote Please review it.

2023-01-19 06:10 UTC, MrBehl06 commented
@leecalcote @GaganpreetKaurKalsi Please help me why there is an error and test failure in this pr.

2023-01-22 06:02 UTC, leecalcote commented
@MrBehl06 because one of the commits isn't signed off (follow the instructions provide for a permanent solution. follow these for this PR - https://github.com/meshery/meshery.io/pull/965/checks?check_run_id=10744634801). 

Also, this PR has a number of other people's commits that are likely included unintentionally (resync your fork).

2023-01-22 06:02 UTC, leecalcote commented
A couple of merge conflicts have arisen.

2023-01-22 06:04 UTC, MrBehl06 commented
Okey @leecalcote thank you.

2023-01-22 06:04 UTC, leecalcote requested changes
Resync fork, sign commits, eliminate merge conflicts

2023-01-26 20:11 UTC, leecalcote requested changes
@MrBehl06 Follow these instructions to sync your fork - https://github.com/meshery/meshery/blob/master/docs/CONTRIBUTING-gitflow.md#fetch-upstream-master-and-merge-with-your-repos-master-branch

2023-03-23 01:53 UTC, closed without merging