Docs added for dark theme
meshery/meshery.io pull request #968
Opened 2023-01-13 10:11 UTC by Shivam-AfA

**Description**

This PR fixes #922 

**Notes for Reviewers**
This PR adds the documentation for new contributers to understand how they can contribute to Meshery.io website based on light and dark theme features on the website.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-01-13 10:16 UTC, Shivam-AfA commented on images/Kuma.svg
> -<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" x="0" y="0" version="1.1" viewBox="0 0 400 400" xml:space="preserve" style="enable-background:new 0 0 4
Ignore please.

2023-01-13 16:32 UTC, leecalcote submitted a review, later dismissed
LGTM

2023-01-14 15:37 UTC, GaganpreetKaurKalsi requested changes
A spelling error 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/54144759/212480068-abcff0f9-0791-4e62-a56f-231074b195bb.png">

2023-01-14 17:21 UTC, Shivam-AfA commented
> A spelling error <img alt="image" width="916" src="https://user-images.githubusercontent.com/54144759/212480068-abcff0f9-0791-4e62-a56f-231074b195bb.png">

Corrected. @GaganpreetKaurKalsi

2023-01-14 18:55 UTC, GaganpreetKaurKalsi approved these changes
All good 💯

2023-01-16 11:16 UTC, eeshaanSA approved these changes
Looks Neat. :+1:

2023-01-16 21:37 UTC, Shivam-AfA commented
@leecalcote I think this PR is all set to be merged.

2023-01-16 21:51 UTC, merged

2023-01-16 21:52 UTC, leecalcote commented
Good deal. 👏