made community newsletter form same
meshery/meshery.io pull request #990
Opened 2023-01-20 16:06 UTC by Adi-ty

Signed-off-by: Aditya <adityasinghboss1234@gmail.com>

This PR makes the community newsletter form to have similar casing in all pages please review and merge this PR or suggest changes if needed

This PR fixes #987 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-01-20 19:45 UTC, Adi-ty commented
@GaganpreetKaurKalsi please review and merge or suggest changes if needed

2023-01-21 15:09 UTC, leecalcote requested changes
Thanks, @Adi-ty. When choosing a consistent format, it should either be:

"Community Newsletter" or all uppercase, but not all lowercase.

2023-01-21 16:13 UTC, Adi-ty commented
Ok I'll fix it

2023-01-21 16:46 UTC, Adi-ty commented
@leecalcote  I have Changed it to "Community Newsletter" 

/#getting-started
<img width="926" alt="image" src="https://user-images.githubusercontent.com/92062352/213877370-c07699a7-fd20-4b4a-b088-4e5a18935f23.png">

/programs
<img width="710" alt="image" src="https://user-images.githubusercontent.com/92062352/213877397-f23f00b7-bd11-4fd5-9ea8-cdd6c2c5469c.png">

/subscribe
<img width="947" alt="image" src="https://user-images.githubusercontent.com/92062352/213877415-efcc41fe-25f8-492a-9fd7-04a449f7f6e5.png">

2023-01-21 16:54 UTC, Adi-ty commented
I just saw that the community newsletter form on `/programs` page has an extra 50px margin below the heading should I remove that also @leecalcote

2023-01-21 17:47 UTC, GaganpreetKaurKalsi requested changes
Sure, remove that extra margin. Also capitalise `Subscribe` as well.

2023-01-21 18:08 UTC, Adi-ty commented
OK will do it

2023-01-21 18:18 UTC, Adi-ty commented
Has done all the changes required @leecalcote @GaganpreetKaurKalsi

2023-01-21 18:23 UTC, GaganpreetKaurKalsi submitted a review, later dismissed
Looks good now 👍 Thanks @Adi-ty 💯

2023-01-22 12:44 UTC, Adi-ty commented
@leecalcote please review this PR.

2023-01-22 13:08 UTC, leecalcote commented
Will you also have a look into the mismatched border radius and white stroke/border?

2023-01-22 13:48 UTC, Adi-ty commented
Should I make changes for every border radius including the whole form, various inputs and subscribe button and also can you elaborate on white stroke/border.

2023-01-22 18:23 UTC, Adi-ty commented
Ok I am making every form have a border radius of 10px and also, I will remove the white outline on subscribe button on one of the page.

2023-01-22 18:28 UTC, Adi-ty commented
@leecalcote I have made all the changes please review and merge

2023-01-23 18:26 UTC, GaganpreetKaurKalsi approved these changes
LGTM 👍

2023-01-26 16:55 UTC, leecalcote commented on _includes/homePage.html
> +        <!-- outline: 1px solid white; -->
```suggestion```

2023-01-26 16:56 UTC, leecalcote commented on _sass/forms.scss
> +	border-radius: 10px;
```suggestion
	border-radius: 0.625rem;
```

2023-01-26 16:58 UTC, leecalcote commented on _includes/homePage.html
> +        <!-- outline: 1px solid white; -->
```suggestion
```

2023-01-26 16:58 UTC, leecalcote approved these changes
Thanks, @Adi-ty

2023-01-26 16:58 UTC, merged